// ============================================================
// PF2e Remaster 日本語データベース — 全599エントリ
// ============================================================

const DB = {};

// ─────────────────────────────────────
// 祖先 (Ancestries)
// ─────────────────────────────────────
DB.ancestries = [
	{
		id: 'human',
		name: 'ヒューマン',
		nameEn: 'Human',
		hp: 8,
		size: '中型',
		speed: 25,
		boosts: ['自由', '自由'],
		flaws: [],
		desc: '適応力に優れた種族。自由な能力値ブーストを2つ得る。多彩な遺産と特技が利用可能。',
		traits: ['ヒューマン', 'ヒューマノイド'],
	},
	{
		id: 'elf',
		name: 'エルフ',
		nameEn: 'Elf',
		hp: 6,
		size: '中型',
		speed: 30,
		boosts: ['敏捷', '知力', '自由'],
		flaws: ['耐久'],
		desc: '優雅で長命な種族。敏捷と知力にブースト、耐久にフロー。暗視と長い寿命を持つ。',
		traits: ['エルフ', 'ヒューマノイド'],
	},
	{
		id: 'dwarf',
		name: 'ドワーフ',
		nameEn: 'Dwarf',
		hp: 10,
		size: '中型',
		speed: 20,
		boosts: ['耐久', '判断', '自由'],
		flaws: ['魅力'],
		desc: '頑健な山岳種族。耐久と判断にブースト、魅力にフロー。暗視と毒への抵抗を持つ。',
		traits: ['ドワーフ', 'ヒューマノイド'],
	},
	{
		id: 'gnome',
		name: 'ノーム',
		nameEn: 'Gnome',
		hp: 8,
		size: '小型',
		speed: 25,
		boosts: ['耐久', '魅力', '自由'],
		flaws: ['筋力'],
		desc: '好奇心旺盛な小さき種族。フェイに縁があり、生来の魔法能力を持つ。',
		traits: ['ノーム', 'ヒューマノイド'],
	},
	{
		id: 'goblin',
		name: 'ゴブリン',
		nameEn: 'Goblin',
		hp: 6,
		size: '小型',
		speed: 25,
		boosts: ['敏捷', '魅力', '自由'],
		flaws: ['判断'],
		desc: '素早く大胆な小型種族。火と歌を愛する。暗視を持つ。',
		traits: ['ゴブリン', 'ヒューマノイド'],
	},
	{
		id: 'halfling',
		name: 'ハーフリング',
		nameEn: 'Halfling',
		hp: 6,
		size: '小型',
		speed: 25,
		boosts: ['敏捷', '判断', '自由'],
		flaws: ['筋力'],
		desc: '幸運で勇敢な小さき民。恐怖への耐性を持つ。',
		traits: ['ハーフリング', 'ヒューマノイド'],
	},
	{
		id: 'orc',
		name: 'オーク',
		nameEn: 'Orc',
		hp: 10,
		size: '中型',
		speed: 25,
		boosts: ['筋力', '自由'],
		flaws: [],
		desc: '力強く不屈の種族。暗視とオーク・フェロシティ（倒れない特性）を持つ。',
		traits: ['オーク', 'ヒューマノイド'],
	},
];

// ─────────────────────────────────────
// 遺産 (Heritages)
// ─────────────────────────────────────
DB.heritages = [
	{
		id: 'versatile_human',
		name: '多才なヒューマン',
		ancestry: 'human',
		desc: '1レベルで追加の一般特技を得る。',
	},
	{
		id: 'skilled_human',
		name: '熟練ヒューマン',
		ancestry: 'human',
		desc: '追加の訓練済み技能を1つ得る。',
	},
	{
		id: 'half_elf',
		name: 'ハーフエルフ',
		ancestry: 'human',
		desc: 'エルフの特技にもアクセス可能。薄暗い視覚を持つ。',
	},
	{
		id: 'half_orc',
		name: 'ハーフオーク',
		ancestry: 'human',
		desc: 'オークの特技にもアクセス可能。薄暗い視覚を持つ。',
	},
	{
		id: 'cavern_elf',
		name: '洞窟エルフ',
		ancestry: 'elf',
		desc: '暗視を持つ。地下世界に適応したエルフ。',
	},
	{
		id: 'woodland_elf',
		name: '森林エルフ',
		ancestry: 'elf',
		desc: '移動速度+5フィート。森林地帯で優位。',
	},
	{
		id: 'ancient_blood_dwarf',
		name: '古き血のドワーフ',
		ancestry: 'dwarf',
		desc: '魔法への抵抗+1。呪文に対するセーヴにボーナス。',
	},
	{
		id: 'forge_dwarf',
		name: '鍛冶ドワーフ',
		ancestry: 'dwarf',
		desc: '火炎ダメージへの抵抗を持つ。',
	},
	{
		id: 'fey_touched_gnome',
		name: 'フェイに触れしノーム',
		ancestry: 'gnome',
		desc: '原始のキャントリップを1つ得る。',
	},
	{
		id: 'sensate_gnome',
		name: '感覚ノーム',
		ancestry: 'gnome',
		desc: '薄暗い視覚の代わりに暗視を得る。',
	},
	{
		id: 'razortooth_goblin',
		name: '剃刀歯ゴブリン',
		ancestry: 'goblin',
		desc: '顎による素手攻撃（1d6刺突）を得る。',
	},
	{
		id: 'unbreakable_goblin',
		name: '不壊ゴブリン',
		ancestry: 'goblin',
		desc: 'HP+4。転倒ダメージ軽減。',
	},
	{
		id: 'gutsy_halfling',
		name: '根性ハーフリング',
		ancestry: 'halfling',
		desc: '感情効果に対するセーヴに+1状況ボーナス。',
	},
	{
		id: 'hillock_halfling',
		name: '丘陵ハーフリング',
		ancestry: 'halfling',
		desc: '休息時の回復量が増加。',
	},
	{
		id: 'badlands_orc',
		name: '荒地オーク',
		ancestry: 'orc',
		desc: '環境による疲労に対する耐性。極端な気温への適応。',
	},
	{
		id: 'hold_scarred_orc',
		name: '傷跡オーク',
		ancestry: 'orc',
		desc: 'HP+4。傷からの回復が速い。',
	},
];

// ─────────────────────────────────────
// 背景 (Backgrounds)
// ─────────────────────────────────────
DB.backgrounds = [
	{
		id: 'acolyte',
		name: '侍祭',
		nameEn: 'Acolyte',
		boosts: ['判断', '自由'],
		skill: '宗教',
		feat: '追加知識（経典）',
		desc: '寺院や聖堂で宗教的な修行を積んだ。',
	},
	{
		id: 'criminal',
		name: '犯罪者',
		nameEn: 'Criminal',
		boosts: ['敏捷', '自由'],
		skill: '隠密',
		feat: '経験的知識（裏社会）',
		desc: '法の外で暮らし、裏社会に精通している。',
	},
	{
		id: 'entertainer',
		name: '芸人',
		nameEn: 'Entertainer',
		boosts: ['魅力', '自由'],
		skill: '芸能',
		feat: '魅力的な芸能',
		desc: '舞台や酒場で観客を楽しませてきた。',
	},
	{
		id: 'farmhand',
		name: '農夫',
		nameEn: 'Farmhand',
		boosts: ['耐久', '自由'],
		skill: '運動',
		feat: '力仕事の達人',
		desc: '農場で体を鍛え、大地と共に生きてきた。',
	},
	{
		id: 'guard',
		name: '衛兵',
		nameEn: 'Guard',
		boosts: ['筋力', '自由'],
		skill: '威圧',
		feat: '迅速な強制',
		desc: '都市の門や城壁を守る任務に就いていた。',
	},
	{
		id: 'hermit',
		name: '隠者',
		nameEn: 'Hermit',
		boosts: ['判断', '自由'],
		skill: '自然',
		feat: '地形の専門家',
		desc: '人里離れた場所で自然と共に暮らしてきた。',
	},
	{
		id: 'merchant',
		name: '商人',
		nameEn: 'Merchant',
		boosts: ['魅力', '自由'],
		skill: '外交',
		feat: '交渉の達人',
		desc: '交易路を旅し、商売の技術を磨いた。',
	},
	{
		id: 'noble',
		name: '貴族',
		nameEn: 'Noble',
		boosts: ['魅力', '自由'],
		skill: '交渉',
		feat: '印象操作',
		desc: '名家の出身で、社交界に精通している。',
	},
	{
		id: 'scholar',
		name: '学者',
		nameEn: 'Scholar',
		boosts: ['知力', '自由'],
		skill: '神秘学/自然/宗教（選択）',
		feat: '確実な知識',
		desc: '学問に打ち込み、広範な知識を蓄えた。',
	},
	{
		id: 'scout',
		name: '斥候',
		nameEn: 'Scout',
		boosts: ['敏捷', '自由'],
		skill: '生存',
		feat: '地形に潜む',
		desc: '野外での偵察任務を行ってきた。',
	},
	{
		id: 'warrior',
		name: '戦士',
		nameEn: 'Warrior',
		boosts: ['筋力', '自由'],
		skill: '威圧',
		feat: '威嚇的な視線',
		desc: '戦場で武勇を磨き、戦いに生きてきた。',
	},
	{
		id: 'artisan',
		name: '職人',
		nameEn: 'Artisan',
		boosts: ['知力', '自由'],
		skill: '製作',
		feat: '専門的製作',
		desc: '工房で技術を磨き、精巧な品を生み出してきた。',
	},
];

// ─────────────────────────────────────
// クラス (Classes)
// ─────────────────────────────────────
DB.classes = [
	{
		id: 'fighter',
		name: 'ファイター',
		nameEn: 'Fighter',
		hp: 10,
		keyAbility: '筋力 or 敏捷',
		perception: '上級者',
		fortitude: '上級者',
		reflex: '上級者',
		will: '訓練済',
		skills: 3,
		attackProf: '伝説級',
		defenseProf: '上級者',
		traditions: [],
		spellcasting: false,
		desc: '武器戦闘の達人。全クラス中最高の攻撃習熟を持ち、あらゆる武器を使いこなす。',
	},
	{
		id: 'wizard',
		name: 'ウィザード',
		nameEn: 'Wizard',
		hp: 6,
		keyAbility: '知力',
		perception: '訓練済',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 2,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['秘術'],
		spellcasting: true,
		desc: '秘術の伝統を操る学究的な魔法使い。呪文書から毎日呪文を準備する。',
	},
	{
		id: 'cleric',
		name: 'クレリック',
		nameEn: 'Cleric',
		hp: 8,
		keyAbility: '判断',
		perception: '訓練済',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 2,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['神術'],
		spellcasting: true,
		desc: '神格に仕える聖職者。ヒールまたはハームの神聖なる源を持つ。',
	},
	{
		id: 'bard',
		name: 'バード',
		nameEn: 'Bard',
		hp: 8,
		keyAbility: '魅力',
		perception: '上級者',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 4,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['オカルト'],
		spellcasting: true,
		desc: '音楽と知識の力を操る呪文使い。味方を鼓舞し敵を弱体化する。',
	},
	{
		id: 'rogue',
		name: 'ローグ',
		nameEn: 'Rogue',
		hp: 8,
		keyAbility: '敏捷',
		perception: '上級者',
		fortitude: '訓練済',
		reflex: '上級者',
		will: '上級者',
		skills: 8,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '技能と急所攻撃の達人。罠解除、隠密行動、交渉に優れる。',
	},
	{
		id: 'ranger',
		name: 'レンジャー',
		nameEn: 'Ranger',
		hp: 10,
		keyAbility: '筋力 or 敏捷',
		perception: '上級者',
		fortitude: '上級者',
		reflex: '上級者',
		will: '訓練済',
		skills: 4,
		attackProf: '上級者',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '野外の専門家にして狩人。獲物を指定して追跡・攻撃に優れる。',
	},
	{
		id: 'monk',
		name: 'モンク',
		nameEn: 'Monk',
		hp: 10,
		keyAbility: '筋力 or 敏捷',
		perception: '訓練済',
		fortitude: '上級者',
		reflex: '上級者',
		will: '上級者',
		skills: 4,
		attackProf: '訓練済',
		defenseProf: '上級者',
		traditions: [],
		spellcasting: false,
		desc: '素手戦闘と気の力の達人。高い防御力と機動力を持つ。',
	},
	{
		id: 'champion',
		name: 'チャンピオン',
		nameEn: 'Champion',
		hp: 10,
		keyAbility: '筋力 or 敏捷',
		perception: '訓練済',
		fortitude: '上級者',
		reflex: '訓練済',
		will: '上級者',
		skills: 2,
		attackProf: '上級者',
		defenseProf: '伝説級',
		traditions: ['神術（集中呪文のみ）'],
		spellcasting: false,
		desc: '信仰の力で戦う聖戦士。全クラス最高の防御習熟と信仰の反応能力を持つ。',
	},
	{
		id: 'druid',
		name: 'ドルイド',
		nameEn: 'Druid',
		hp: 8,
		keyAbility: '判断',
		perception: '訓練済',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 4,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['原始'],
		spellcasting: true,
		desc: '自然の力を操る呪文使い。野生変身、動物の仲間、嵐の力などを選択。',
	},
	{
		id: 'sorcerer',
		name: 'ソーサラー',
		nameEn: 'Sorcerer',
		hp: 6,
		keyAbility: '魅力',
		perception: '訓練済',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 3,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['血脈により選択（秘術/神術/オカルト/原始）'],
		spellcasting: true,
		desc: '生来の魔力を持つ術者。血脈により呪文伝統が決まり、呪文レパートリーを使用。',
	},
	{
		id: 'barbarian',
		name: 'バーバリアン',
		nameEn: 'Barbarian',
		hp: 12,
		keyAbility: '筋力',
		perception: '上級者',
		fortitude: '上級者',
		reflex: '訓練済',
		will: '上級者',
		skills: 3,
		attackProf: '上級者',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '激怒の力で戦う野蛮な戦士。最高のHPと激怒による追加ダメージを持つ。',
	},
	{
		id: 'alchemist',
		name: 'アルケミスト',
		nameEn: 'Alchemist',
		hp: 8,
		keyAbility: '知力',
		perception: '訓練済',
		fortitude: '上級者',
		reflex: '上級者',
		will: '訓練済',
		skills: 3,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '錬金術の力でアイテムを創造する科学者。爆弾・変異薬・エリクサーを作成。',
	},
	{
		id: 'witch',
		name: 'ウィッチ',
		nameEn: 'Witch',
		hp: 6,
		keyAbility: '知力',
		perception: '訓練済',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 3,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['パトロンにより選択'],
		spellcasting: true,
		desc: 'パトロンから力を授かる魔女。使い魔とヘックス（呪い）の集中呪文を操る。',
	},
	{
		id: 'swashbuckler',
		name: 'スワッシュバックラー',
		nameEn: 'Swashbuckler',
		hp: 10,
		keyAbility: '敏捷',
		perception: '上級者',
		fortitude: '訓練済',
		reflex: '上級者',
		will: '上級者',
		skills: 5,
		attackProf: '上級者',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '華麗な剣技で戦う冒険家。鍛冶場（パナッシュ）とフィニッシュによる一撃必殺。',
	},
	{
		id: 'investigator',
		name: 'インヴェスティゲーター',
		nameEn: 'Investigator',
		hp: 8,
		keyAbility: '知力',
		perception: '上級者',
		fortitude: '訓練済',
		reflex: '上級者',
		will: '上級者',
		skills: 6,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '観察と推理の達人。手がかりを追い、戦闘でも知略を活かす。',
	},
	{
		id: 'oracle',
		name: 'オラクル',
		nameEn: 'Oracle',
		hp: 8,
		keyAbility: '魅力',
		perception: '訓練済',
		fortitude: '訓練済',
		reflex: '訓練済',
		will: '上級者',
		skills: 3,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['神術'],
		spellcasting: true,
		desc: '呪いと共に神秘を授かった神託者。呪いが深まるほど強力な力を発揮。',
	},
	{
		id: 'gunslinger',
		name: 'ガンスリンガー',
		nameEn: 'Gunslinger',
		hp: 8,
		keyAbility: '敏捷',
		perception: '上級者',
		fortitude: '上級者',
		reflex: '上級者',
		will: '訓練済',
		skills: 3,
		attackProf: '上級者',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '銃器の達人。リロードと射撃の技術を極め、致命的な一撃を放つ。',
	},
	{
		id: 'inventor',
		name: 'インヴェンター',
		nameEn: 'Inventor',
		hp: 8,
		keyAbility: '知力',
		perception: '訓練済',
		fortitude: '上級者',
		reflex: '訓練済',
		will: '上級者',
		skills: 3,
		attackProf: '上級者',
		defenseProf: '訓練済',
		traditions: [],
		spellcasting: false,
		desc: '革新的な発明家。武器・防具・コンストラクトを改造して戦う。',
	},
	{
		id: 'magus',
		name: 'マグス',
		nameEn: 'Magus',
		hp: 8,
		keyAbility: '筋力 or 敏捷',
		perception: '訓練済',
		fortitude: '上級者',
		reflex: '訓練済',
		will: '上級者',
		skills: 2,
		attackProf: '上級者',
		defenseProf: '訓練済',
		traditions: ['秘術'],
		spellcasting: true,
		desc: '剣と魔法を融合させる戦士。スペルストライクで呪文を打撃に乗せる。',
	},
	{
		id: 'kineticist',
		name: 'キネティシスト',
		nameEn: 'Kineticist',
		hp: 8,
		keyAbility: '耐久',
		perception: '訓練済',
		fortitude: '上級者',
		reflex: '上級者',
		will: '訓練済',
		skills: 3,
		attackProf: '訓練済',
		defenseProf: '訓練済',
		traditions: ['元素（特殊）'],
		spellcasting: false,
		desc: '元素の力を直接操る能力者。火・水・地・風・木・金属の元素を選択。',
	},
];

// ─────────────────────────────────────
// 能力値 (Abilities)
// ─────────────────────────────────────
DB.abilities = [
	{
		id: 'str',
		name: '筋力',
		nameEn: 'Strength',
		abbr: 'STR',
		desc: '近接攻撃、ダメージ、運動判定に影響。',
	},
	{
		id: 'dex',
		name: '敏捷',
		nameEn: 'Dexterity',
		abbr: 'DEX',
		desc: 'AC、遠隔攻撃、反応セーヴ、隠密に影響。',
	},
	{
		id: 'con',
		name: '耐久',
		nameEn: 'Constitution',
		abbr: 'CON',
		desc: 'HP、頑健セーヴに影響。',
	},
	{
		id: 'int',
		name: '知力',
		nameEn: 'Intelligence',
		abbr: 'INT',
		desc: '技能数、秘術/工芸/知識判定に影響。',
	},
	{
		id: 'wis',
		name: '判断',
		nameEn: 'Wisdom',
		abbr: 'WIS',
		desc: '知覚、意志セーヴ、神術/原始呪文DCに影響。',
	},
	{
		id: 'cha',
		name: '魅力',
		nameEn: 'Charisma',
		abbr: 'CHA',
		desc: '交渉、威圧、オカルト/神術（一部）呪文DCに影響。',
	},
];

// ─────────────────────────────────────
// 技能 (Skills)
// ─────────────────────────────────────
DB.skills = [
	{
		id: 'acrobatics',
		name: '軽業',
		nameEn: 'Acrobatics',
		ability: '敏捷',
		desc: 'バランス、飛行操作、空中回避に使用。',
	},
	{
		id: 'arcana',
		name: '神秘学',
		nameEn: 'Arcana',
		ability: '知力',
		desc: '秘術に関する知識の想起、秘術アイテムの鑑定に使用。',
	},
	{
		id: 'athletics',
		name: '運動',
		nameEn: 'Athletics',
		ability: '筋力',
		desc: '登攀、水泳、跳躍、組み付き、突き飛ばし、足払いに使用。',
	},
	{
		id: 'crafting',
		name: '製作',
		nameEn: 'Crafting',
		ability: '知力',
		desc: 'アイテムの製作、修理、鑑定に使用。',
	},
	{
		id: 'deception',
		name: '欺瞞',
		nameEn: 'Deception',
		ability: '魅力',
		desc: '嘘、変装、フェイントに使用。',
	},
	{
		id: 'diplomacy',
		name: '外交',
		nameEn: 'Diplomacy',
		ability: '魅力',
		desc: '説得、交渉、印象操作に使用。',
	},
	{
		id: 'intimidation',
		name: '威圧',
		nameEn: 'Intimidation',
		ability: '魅力',
		desc: '脅迫、士気くじき（デモラライズ）に使用。',
	},
	{
		id: 'lore',
		name: '伝承',
		nameEn: 'Lore',
		ability: '知力',
		desc: '特定分野の専門知識。分野を選択して取得。',
	},
	{
		id: 'medicine',
		name: '医術',
		nameEn: 'Medicine',
		ability: '判断',
		desc: '応急手当、傷の治療、病気の診断に使用。',
	},
	{
		id: 'nature',
		name: '自然',
		nameEn: 'Nature',
		ability: '判断',
		desc: '自然に関する知識、動物の扱いに使用。',
	},
	{
		id: 'occultism',
		name: 'オカルト',
		nameEn: 'Occultism',
		ability: '知力',
		desc: 'オカルトに関する知識、超自然現象の鑑定に使用。',
	},
	{
		id: 'performance',
		name: '芸能',
		nameEn: 'Performance',
		ability: '魅力',
		desc: '歌、楽器演奏、演技に使用。',
	},
	{
		id: 'religion',
		name: '宗教',
		nameEn: 'Religion',
		ability: '判断',
		desc: '宗教に関する知識、神格の教義の理解に使用。',
	},
	{
		id: 'society',
		name: '社会',
		nameEn: 'Society',
		ability: '知力',
		desc: '社会制度、法律、歴史の知識、暗号解読に使用。',
	},
	{
		id: 'stealth',
		name: '隠密',
		nameEn: 'Stealth',
		ability: '敏捷',
		desc: '潜伏、忍び歩き、尾行に使用。',
	},
	{
		id: 'survival',
		name: '生存',
		nameEn: 'Survival',
		ability: '判断',
		desc: '追跡、方角判断、野外での生存に使用。',
	},
	{
		id: 'thievery',
		name: '窃盗',
		nameEn: 'Thievery',
		ability: '敏捷',
		desc: '開錠、スリ、罠解除に使用。',
	},
];

// ─────────────────────────────────────
// 状態異常 (Conditions)
// ─────────────────────────────────────
DB.conditions = [
	{
		name: '盲目',
		nameEn: 'Blinded',
		desc: '何も見えない。視覚に依存する判定は自動失敗。全ての生物はあなたに対して隠蔽状態。',
	},
	{
		name: '恐怖',
		nameEn: 'Frightened',
		desc: '恐怖N。全ての判定とDCに-Nのペナルティ。ターン終了時にN-1に減少。',
	},
	{
		name: '病気',
		nameEn: 'Sickened',
		desc: '病気N。全ての判定とDCに-Nのペナルティ。嘔吐アクション（頑健セーヴ）で軽減可能。',
	},
	{
		name: '減速',
		nameEn: 'Slowed',
		desc: '減速N。ターン開始時にNアクション分のアクションが減少する。',
	},
	{
		name: '朦朧',
		nameEn: 'Stunned',
		desc: '朦朧N。Nアクション分のアクションを使用不可。',
	},
	{
		name: '麻痺',
		nameEn: 'Paralyzed',
		desc: '体が完全に動かない。ACに-4状況ペナルティ。頑健セーヴで回復可能。',
	},
	{
		name: '無力化',
		nameEn: 'Unconscious',
		desc: '意識がない。知覚不可。ACに-4。頑健と反応のセーヴは自動的に大失敗。',
	},
	{
		name: '瀕死',
		nameEn: 'Dying',
		desc: '瀕死N。ターン開始時に回復判定（DC10+N）。N=4で死亡。安定化で気絶状態に。',
	},
	{
		name: '転倒',
		nameEn: 'Prone',
		desc: '地面に伏せている。立ち上がりに1アクション。近接攻撃に-2、遠隔攻撃に+2の状況修正。',
	},
	{
		name: 'つかまれた',
		nameEn: 'Grabbed',
		desc: 'つかんでいる相手に拘束されている。拘束状態になり、身動きが取れない。',
	},
	{
		name: '疲労',
		nameEn: 'Fatigued',
		desc: 'ACとセーヴに-1状況ペナルティ。探索・移動に影響。休息で回復。',
	},
	{
		name: '衰弱',
		nameEn: 'Enfeebled',
		desc: '衰弱N。筋力の判定とDCに-Nのペナルティ。',
	},
	{
		name: '不器用',
		nameEn: 'Clumsy',
		desc: '不器用N。敏捷の判定とDCに-Nのペナルティ。',
	},
	{
		name: '愚鈍',
		nameEn: 'Stupefied',
		desc: '愚鈍N。精神系の判定とDCに-N。呪文使用時に平目判定（DC5+N）失敗で呪文消失。',
	},
	{
		name: '落ち込み',
		nameEn: 'Drained',
		desc: '落ち込みN。耐久の判定に-N。最大HPがレベル×N減少。',
	},
	{
		name: '不可視',
		nameEn: 'Invisible',
		desc: '視覚的に感知できない。他者に対して隠蔽（ミスチャンス20%）。',
	},
	{
		name: '隠蔽',
		nameEn: 'Concealed',
		desc: 'DC5平目に失敗すると攻撃が外れる。薄暗い場所や霧の中で適用。',
	},
	{
		name: '挟撃',
		nameEn: 'Off-Guard (Flat-Footed)',
		desc: 'ACに-2状況ペナルティ。挟撃やフェイント成功時に適用。',
	},
	{
		name: '加速',
		nameEn: 'Quickened',
		desc: '毎ターン追加で1アクションを得る（制限付き）。',
	},
	{
		name: '持続ダメージ',
		nameEn: 'Persistent Damage',
		desc: 'ターン終了時にダメージを受ける。DC15平目判定に成功で終了。',
	},
	{
		name: '石化',
		nameEn: 'Petrified',
		desc: '石に変えられた。無力化＋物理抵抗。特殊な手段でのみ回復。',
	},
	{
		name: '魅了',
		nameEn: 'Fascinated',
		desc: '特定の対象に集中。他の行動に-2ペナルティ。敵対行為で解除。',
	},
	{
		name: '混乱',
		nameEn: 'Confused',
		desc: '行動をランダムに決定。味方を攻撃する可能性あり。',
	},
	{
		name: '支配',
		nameEn: 'Controlled',
		desc: '他者に完全に支配されている。その者の命令通りに行動する。',
	},
	{
		name: '死亡',
		nameEn: 'Dead',
		desc: '生命活動が停止。蘇生呪文でのみ回復可能。',
	},
];

// ─────────────────────────────────────
// 呪文 (Spells) — キャントリップ〜ランク10
// ─────────────────────────────────────
DB.spells = [
	// === キャントリップ ===
	{
		name: 'エレクトリック・アーク',
		nameEn: 'Electric Arc',
		rank: 0,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '2体の敵に電撃ダメージ。キャントリップの中で最高効率のダメージ。',
		heighten: 'レベルに応じてダメージダイス増加。',
	},
	{
		name: 'シールド',
		nameEn: 'Shield',
		rank: 0,
		traditions: ['秘術', '神術', 'オカルト'],
		actions: 1,
		defense: '—',
		desc: 'ACに+1状況ボーナス。リアクションでダメージをブロック可能。',
		heighten: '硬度がランクに応じて増加。',
	},
	{
		name: 'テレキネティック・プロジェクタイル',
		nameEn: 'Telekinetic Projectile',
		rank: 0,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '呪文攻撃',
		desc: '物体を念力で投擲。物理ダメージタイプを選択可能。',
		heighten: 'ダメージダイス増加。',
	},
	{
		name: 'イグニション',
		nameEn: 'Ignition',
		rank: 0,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '呪文攻撃 or 基本反応',
		desc: '火炎ダメージ。近接使用でダイスがd6に増加。',
		heighten: 'ダメージダイス増加。',
	},
	{
		name: 'ゴウジング・クロー',
		nameEn: 'Gouging Claw',
		rank: 0,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '呪文攻撃',
		desc: '近接呪文攻撃。命中時に持続出血ダメージも付与。',
		heighten: 'ダメージダイス増加。',
	},
	{
		name: 'ディテクト・マジック',
		nameEn: 'Detect Magic',
		rank: 0,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '30フィート放射内の魔法のオーラを感知する。',
		heighten: 'ランク3で正確な位置を特定。ランク5で魔法の伝統を識別。',
	},
	{
		name: 'ライト',
		nameEn: 'Light',
		rank: 0,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '明るい光を放つ。20フィート照明。4つまで同時維持可能。',
		heighten: 'ランク4で薄暗い光の範囲拡大。',
	},
	{
		name: 'ガイダンス',
		nameEn: 'Guidance',
		rank: 0,
		traditions: ['神術', 'オカルト', '原始'],
		actions: 1,
		defense: '—',
		desc: '1回の判定に+1状況ボーナス。使用後1時間クールダウン。',
		heighten: 'なし。',
	},
	{
		name: 'ニードル・ダーツ',
		nameEn: 'Needle Darts',
		rank: 0,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '呪文攻撃',
		desc: '金属の針を射出。特殊金属で弱点を突ける。',
		heighten: 'ダメージダイス増加。',
	},
	{
		name: 'ディヴァイン・ランス',
		nameEn: 'Divine Lance',
		rank: 0,
		traditions: ['神術'],
		actions: 2,
		defense: '呪文攻撃',
		desc: '霊的ダメージの光線。抵抗されにくいダメージタイプ。',
		heighten: 'ダメージダイス増加。',
	},

	// === ランク1 ===
	{
		name: 'ヒール',
		nameEn: 'Heal',
		rank: 1,
		traditions: ['神術', '原始'],
		actions: '1〜3',
		defense: '—（味方）/ 基本頑健（アンデッド）',
		desc: '1アクション:接触1d8回復。2アクション:30ft 1d8+8回復。3アクション:30ft放射で全味方回復＆アンデッドにダメージ。',
		heighten: 'ランクごとに1d8追加。',
	},
	{
		name: 'フォースバラージ',
		nameEn: 'Force Barrage',
		rank: 1,
		traditions: ['秘術', 'オカルト'],
		actions: '1〜3',
		defense: '—（自動命中）',
		desc: '1d4+1力場ダメージのミサイル。自動命中。アクション数に応じて1〜3発。',
		heighten: '2ランクごとにミサイル+1発。',
	},
	{
		name: 'フィアー',
		nameEn: 'Fear',
		rank: 1,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '意志',
		desc: '対象を恐怖状態にする。失敗で恐怖2、大失敗で恐怖3（逃走）。',
		heighten: 'ランク3で30ft爆発に拡大。',
	},
	{
		name: 'マジックウェポン',
		nameEn: 'Runic Weapon',
		rank: 1,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '武器に+1ストライキング相当の強化。1分間持続。',
		heighten:
			'ランク4で+2ストライキング、ランク6で+2グレーター・ストライキング。',
	},
	{
		name: 'サンクチュアリ',
		nameEn: 'Sanctuary',
		rank: 1,
		traditions: ['神術', 'オカルト'],
		actions: 2,
		defense: '意志',
		desc: '対象を攻撃しようとする敵は意志セーヴに成功しなければ攻撃不可。',
		heighten: 'なし。',
	},
	{
		name: 'チャーム',
		nameEn: 'Charm',
		rank: 1,
		traditions: ['秘術', 'オカルト', '原始'],
		actions: 2,
		defense: '意志',
		desc: '対象の態度を友好的にする。大失敗で1時間持続。知覚が難しい。',
		heighten: 'ランク4で10体まで。',
	},
	{
		name: 'グリース',
		nameEn: 'Grease',
		rank: 1,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '反応',
		desc: '4マスの地面を滑りやすくする。転倒判定（反応セーヴ）。移動困難地形。',
		heighten: 'なし。',
	},
	{
		name: 'マジックミサイルアーマー',
		nameEn: 'Mystic Armor',
		rank: 1,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: 'ACに+1アイテムボーナス（エクスプローラーズ・クロージングと同等）。',
		heighten: 'ランクに応じてACボーナス増加。',
	},
	{
		name: 'コマンド',
		nameEn: 'Command',
		rank: 1,
		traditions: ['秘術', '神術', 'オカルト'],
		actions: 2,
		defense: '意志',
		desc: '対象に命令を下す（逃走・武器を落とす等）。失敗で従う。',
		heighten: 'ランク5で全生物タイプに有効。',
	},
	{
		name: 'トゥルーストライク',
		nameEn: 'Sure Strike',
		rank: 1,
		traditions: ['秘術', 'オカルト'],
		actions: 1,
		defense: '—',
		desc: '次の攻撃ロールを2回振って高い方を使用する。',
		heighten: 'なし。',
	},

	// === ランク2 ===
	{
		name: '不可視',
		nameEn: 'Invisibility',
		rank: 2,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '対象を不可視にする。攻撃すると解除。10分間持続。',
		heighten: 'ランク4で攻撃しても解除されない（1分間）。',
	},
	{
		name: 'ミラーイメージ',
		nameEn: 'Mirror Image',
		rank: 2,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '3体の幻影の分身を作成。攻撃されるとDC5平目で分身が受ける。1分間。',
		heighten: 'なし。',
	},
	{
		name: 'レジスト・エナジー',
		nameEn: 'Resist Energy',
		rank: 2,
		traditions: ['秘術', '神術', '原始', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '選択した元素に対するダメージ抵抗5を得る。1時間持続。',
		heighten: 'ランク4で抵抗10、ランク7で抵抗15。',
	},
	{
		name: 'ウェブ',
		nameEn: 'Web',
		rank: 2,
		traditions: ['秘術', '原始'],
		actions: 3,
		defense: '反応',
		desc: '10ft爆発範囲に蜘蛛の巣。移動困難地形。反応セーヴ失敗で拘束。',
		heighten: 'なし。',
	},
	{
		name: '暗闇',
		nameEn: 'Darkness',
		rank: 2,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 3,
		defense: '—',
		desc: '20ft爆発範囲に魔法の暗闇。同ランク以下の魔法の光を無効化。',
		heighten: 'ランク4で暗視も無効化。',
	},
	{
		name: 'ディスペル・マジック',
		nameEn: 'Dispel Magic',
		rank: 2,
		traditions: ['秘術', '神術', '原始', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '対象の魔法効果1つを打ち消す。対抗判定を行う。',
		heighten: '高ランクで対抗ボーナス増加。',
	},
	{
		name: '沈静',
		nameEn: 'Calm',
		rank: 2,
		traditions: ['神術', 'オカルト'],
		actions: 2,
		defense: '意志',
		desc: '10ft爆発範囲内の生物を落ち着かせる。敵対行動不可（意志セーヴ）。最大1分。',
		heighten: 'なし。',
	},
	{
		name: 'サウンドバースト',
		nameEn: 'Sound Burst',
		rank: 2,
		traditions: ['神術', 'オカルト'],
		actions: 2,
		defense: '基本頑健',
		desc: '10ft爆発に2d10音響ダメージ。失敗で朦朧1。',
		heighten: 'ランクごとに+1d10。',
	},
	{
		name: 'ブラッドヴェンデッタ',
		nameEn: 'Blood Vendetta',
		rank: 2,
		traditions: ['秘術', '神術', '原始'],
		actions: 'リアクション',
		defense: '意志',
		desc: '自分にダメージを与えた敵に呪いをかけ、持続出血ダメージを付与。',
		heighten: 'なし。',
	},
	{
		name: 'エンラージ',
		nameEn: 'Enlarge',
		rank: 2,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '—',
		desc: '味方を大型化。リーチ10ft、ダメージ+2、不器用1。1分間。',
		heighten: 'ランク4で超大型化可能。',
	},
	{
		name: 'シャッターリング・ジェム',
		nameEn: 'Revealing Light',
		rank: 2,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '反応',
		desc: '不可視の生物を暴く光。20ft爆発。不可視解除＋隠蔽無効化。',
		heighten: 'なし。',
	},
	{
		name: 'ファイナルサクリファイス',
		nameEn: 'Final Sacrifice',
		rank: 2,
		traditions: ['秘術', '神術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '自分のミニオンを爆発させ20ft爆発。ファイアーボール級のダメージ。',
		heighten: 'ランクごとに+1d6。',
	},

	// === ランク3 ===
	{
		name: 'ファイアーボール',
		nameEn: 'Fireball',
		rank: 3,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '500ft射程、20ft爆発。6d6火炎ダメージ。',
		heighten: 'ランクごとに+2d6。',
	},
	{
		name: 'ヘイスト',
		nameEn: 'Haste',
		rank: 3,
		traditions: ['秘術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '味方1体の速度+10ft。毎ターン追加の打撃アクション。1分間。',
		heighten: 'ランク7で最大6体。',
	},
	{
		name: 'スロー',
		nameEn: 'Slow',
		rank: 3,
		traditions: ['秘術', 'オカルト', '原始'],
		actions: 2,
		defense: '頑健',
		desc: '対象を減速。毎ターン2アクションのみ。失敗で1分間。',
		heighten: 'ランク6で10体まで。',
	},
	{
		name: 'ライトニングボルト',
		nameEn: 'Lightning Bolt',
		rank: 3,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '120ftの直線に4d12電撃ダメージ。',
		heighten: 'ランクごとに+1d12。',
	},
	{
		name: 'ヒロイズム',
		nameEn: 'Heroism',
		rank: 3,
		traditions: ['神術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '攻撃・セーヴ・技能に+1状況ボーナス。10分間。',
		heighten: 'ランク6で+2、ランク9で+3。',
	},
	{
		name: 'ヴァンピリック・フィースト',
		nameEn: 'Vampiric Feast',
		rank: 3,
		traditions: ['秘術', '神術', 'オカルト'],
		actions: 2,
		defense: '基本頑健',
		desc: '接触で6d6ヴォイドダメージ。与えたダメージの半分を回復。',
		heighten: 'ランクごとに+2d6。',
	},
	{
		name: '催眠パターン',
		nameEn: 'Hypnotic Pattern',
		rank: 3,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '意志（無力化）',
		desc: '10ft爆発。失敗で魅了、大失敗で無力化（失神）。',
		heighten: 'なし。',
	},
	{
		name: 'ブラインドネス',
		nameEn: 'Blindness',
		rank: 3,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '頑健（無力化）',
		desc: '対象を永続的に盲目にする。成功で1ラウンド目がくらむ。',
		heighten: 'なし。',
	},
	{
		name: 'サークル・オブ・プロテクション',
		nameEn: 'Circle of Protection',
		rank: 3,
		traditions: ['神術', 'オカルト'],
		actions: 3,
		defense: '—',
		desc: '10ft放射。味方にACボーナスと特定種別への防護効果。10分間。',
		heighten: 'なし。',
	},
	{
		name: 'マウンテン・レジリエンス',
		nameEn: 'Mountain Resilience',
		rank: 3,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '—',
		desc: '物理ダメージへの抵抗5。20分間持続。',
		heighten: 'ランクごとに抵抗+3。',
	},

	// === ランク4 ===
	{
		name: 'フライ',
		nameEn: 'Fly',
		rank: 4,
		traditions: ['秘術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '飛行速度を得る。5分間。落下前に着地の必要あり。',
		heighten: 'なし。',
	},
	{
		name: 'フリーダム',
		nameEn: 'Unfettered Movement',
		rank: 4,
		traditions: ['秘術', '神術', '原始'],
		actions: 2,
		defense: '—',
		desc: '移動を妨げる効果（組み付き・困難地形等）を無視。10分間。',
		heighten: 'なし。',
	},
	{
		name: 'トランスロケート',
		nameEn: 'Translocate',
		rank: 4,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '120ft以内の見える場所に瞬間移動。',
		heighten: 'ランク5で1マイル。',
	},
	{
		name: 'ウォール・オブ・ファイア',
		nameEn: 'Wall of Fire',
		rank: 4,
		traditions: ['秘術', '原始'],
		actions: 3,
		defense: '—',
		desc: '60ftの炎の壁。通過時4d6火炎ダメージ。壁の片側に2d6追加。',
		heighten: 'ランクごとに+1d6。',
	},
	{
		name: 'ディヴァイン・ラス',
		nameEn: 'Divine Wrath',
		rank: 4,
		traditions: ['神術'],
		actions: 2,
		defense: '基本頑健',
		desc: '20ft爆発。4d10霊的ダメージ。失敗で病気1。',
		heighten: 'ランクごとに+1d10。',
	},
	{
		name: 'ソリッド・フォグ',
		nameEn: 'Solid Fog',
		rank: 4,
		traditions: ['秘術', '原始'],
		actions: 3,
		defense: '—',
		desc: '20ft爆発の濃霧。隠蔽+移動困難地形。',
		heighten: 'なし。',
	},
	{
		name: 'ペインフル・ヴァイブレーション',
		nameEn: 'Painful Vibrations',
		rank: 4,
		traditions: ['オカルト'],
		actions: 2,
		defense: '意志',
		desc: '60ft射程。4d10精神ダメージ。失敗で病気状態付与。',
		heighten: 'ランクごとに+1d10。',
	},
	{
		name: 'アニメイトデッド上位',
		nameEn: 'Animate Dead (Rank 4)',
		rank: 4,
		traditions: ['秘術', '神術'],
		actions: 3,
		defense: '—',
		desc: 'レベル4以下のアンデッドクリーチャーを召喚・命令。',
		heighten: 'ランク5でレベル7以下、以降同様に増加。',
	},

	// === ランク5 ===
	{
		name: 'コーン・オブ・コールド',
		nameEn: 'Cone of Cold',
		rank: 5,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '60ft円錐に12d6冷気ダメージ。',
		heighten: 'ランクごとに+2d6。',
	},
	{
		name: 'テレキネシス',
		nameEn: 'Telekinesis',
		rank: 5,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '頑健（生物対象時）',
		desc: '物体を念力で操作。80バルクまで。攻撃にも使用可能。維持で継続。',
		heighten: 'なし。',
	},
	{
		name: 'ブレス・オブ・ライフ',
		nameEn: 'Breath of Life',
		rank: 5,
		traditions: ['神術', '原始'],
		actions: 'リアクション',
		defense: '—',
		desc: '味方が死亡した瞬間にリアクションで蘇生。4d8回復。',
		heighten: 'ランクごとに+1d8。',
	},
	{
		name: 'ウォール・オブ・ストーン',
		nameEn: 'Wall of Stone',
		rank: 5,
		traditions: ['秘術', '原始'],
		actions: 3,
		defense: '—',
		desc: '石の壁を生成。各面HP36・硬度14。維持不要で永続化可能。',
		heighten: 'なし。',
	},
	{
		name: 'シナセシア',
		nameEn: 'Synesthesia',
		rank: 5,
		traditions: ['オカルト'],
		actions: 2,
		defense: '意志',
		desc: '感覚を混乱させ全判定に-3ペナルティ。失敗で1分間持続。',
		heighten: 'ランク9で30ft爆発に拡大。',
	},
	{
		name: 'フレイムストライク',
		nameEn: 'Flame Strike',
		rank: 5,
		traditions: ['神術'],
		actions: 2,
		defense: '基本反応',
		desc: '10ft爆発。8d6ダメージ（半分火炎＋半分霊的）。火炎抵抗では半分しか軽減不可。',
		heighten: 'ランクごとに+2d6。',
	},
	{
		name: 'シャドウブラスト',
		nameEn: 'Shadow Blast',
		rank: 5,
		traditions: ['神術', 'オカルト'],
		actions: 2,
		defense: '基本頑健 or 基本反応',
		desc: '対象1体かエリア（20ft爆発）を選択。ヴォイド/精神ダメージ。',
		heighten: 'ランクごとに+2d6。',
	},
	{
		name: 'クロマティック・ウォール',
		nameEn: 'Chromatic Wall',
		rank: 5,
		traditions: ['秘術', 'オカルト'],
		actions: 3,
		defense: '—',
		desc: '色によって異なる効果の壁。赤=火炎、青=電撃、紫=全て等。',
		heighten: 'ランク7で2色の壁。',
	},

	// === ランク6 ===
	{
		name: 'チェイン・ライトニング',
		nameEn: 'Chain Lightning',
		rank: 6,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '最初の目標に8d12電撃ダメージ。その後最大4体に連鎖。',
		heighten: 'ランクごとに+1d12。',
	},
	{
		name: 'ディスインテグレイト',
		nameEn: 'Disintegrate',
		rank: 6,
		traditions: ['秘術'],
		actions: 2,
		defense: '基本頑健',
		desc: '12d10力場ダメージ。大失敗で+40ダメージ。HP0で完全消滅。',
		heighten: 'ランクごとに+2d10。',
	},
	{
		name: 'トゥルーシーイング',
		nameEn: 'Truesight',
		rank: 6,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '不可視・幻術・変身を見破る。10分間持続。',
		heighten: 'なし。',
	},
	{
		name: 'ブレード・バリア',
		nameEn: 'Blade Barrier',
		rank: 6,
		traditions: ['神術'],
		actions: 3,
		defense: '—',
		desc: '120ftの刃の壁。通過時7d8斬撃ダメージ。',
		heighten: 'ランクごとに+1d8。',
	},
	{
		name: 'スペルターニング',
		nameEn: 'Spell Turning',
		rank: 6,
		traditions: ['秘術'],
		actions: 2,
		defense: '—',
		desc: '自分に向けた呪文を術者に反射。7ランク以下に有効。10分間。',
		heighten: 'なし。',
	},
	{
		name: 'パープルワーム・スティング',
		nameEn: 'Purple Worm Sting',
		rank: 6,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '頑健',
		desc: '接触攻撃。毒ダメージ＋紫蟲毒（段階的に麻痺）。',
		heighten: 'なし。',
	},

	// === ランク7 ===
	{
		name: '次元間テレポート',
		nameEn: 'Interplanar Teleport',
		rank: 7,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 10,
		defense: '—',
		desc: '別の次元界に移動。最大9体同行可能。正確な目的地にはスキル判定。',
		heighten: 'なし。',
	},
	{
		name: 'リジェネレイト',
		nameEn: 'Regenerate',
		rank: 7,
		traditions: ['神術', '原始'],
		actions: 2,
		defense: '—',
		desc: '味方に再生15を付与。毎ラウンドHP回復。酸と火炎で一時停止。1分間。',
		heighten: 'ランク9で再生20。',
	},
	{
		name: 'プリズマティック・スプレー',
		nameEn: 'Prismatic Spray',
		rank: 7,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '呪文ごとに異なる',
		desc: '30ft円錐。ランダムな色の光線で壊滅的効果。石化・死亡・次元追放等。',
		heighten: 'なし。',
	},
	{
		name: 'エナジー・イージス',
		nameEn: 'Energy Aegis',
		rank: 7,
		traditions: ['秘術', '神術', 'オカルト', '原始'],
		actions: 2,
		defense: '—',
		desc: '全元素ダメージへの抵抗5を1時間得る。',
		heighten: 'ランク9で抵抗10。',
	},
	{
		name: 'エクセキュート',
		nameEn: 'Execute',
		rank: 7,
		traditions: ['神術', '原始'],
		actions: 2,
		defense: '基本頑健',
		desc: '70ft射程。大量のヴォイドダメージ。既にダメージを受けた敵に追加効果。',
		heighten: 'ランクごとに+1d6。',
	},
	{
		name: 'テレポート',
		nameEn: 'Teleport',
		rank: 7,
		traditions: ['秘術', 'オカルト'],
		actions: 10,
		defense: '—',
		desc: '100マイル以内の既知の場所に瞬間移動。最大5体まで。',
		heighten: 'なし。',
	},

	// === ランク8 ===
	{
		name: 'アースクエイク',
		nameEn: 'Earthquake',
		rank: 8,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '60ft爆発。11d6殴打ダメージ。地割れ・建造物破壊。転倒。',
		heighten: 'ランクごとに+1d6。',
	},
	{
		name: 'デシケイト',
		nameEn: 'Desiccate',
		rank: 8,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本頑健',
		desc: '30ft爆発。生物から水分を奪い18d6ダメージ。',
		heighten: 'なし。',
	},
	{
		name: 'クアンダリー',
		nameEn: 'Quandary',
		rank: 8,
		traditions: ['秘術'],
		actions: 2,
		defense: '意志（無力化）',
		desc: '対象を朦朧状態にする。大失敗で永続的朦朧。',
		heighten: 'なし。',
	},
	{
		name: 'ディヴァイン・インスピレーション',
		nameEn: 'Divine Inspiration',
		rank: 8,
		traditions: ['神術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '味方に聖なる守護。攻撃者にダメージを反射。15ft放射。1分間。',
		heighten: 'なし。',
	},
	{
		name: 'ヒドゥン・マインド',
		nameEn: 'Hidden Mind',
		rank: 8,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '精神効果と探知魔法に対する完全防御。24時間持続。',
		heighten: 'なし。',
	},
	{
		name: 'ポーラー・レイ',
		nameEn: 'Polar Ray',
		rank: 8,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '呪文攻撃',
		desc: '10d8冷気ダメージ。命中で鈍足2。',
		heighten: 'ランクごとに+2d8。',
	},

	// === ランク9 ===
	{
		name: 'フォーリング・スターズ',
		nameEn: 'Falling Stars',
		rank: 9,
		traditions: ['秘術', '原始'],
		actions: 2,
		defense: '基本反応',
		desc: '4つの40ft爆発。各6d10殴打+6d6火炎ダメージ。重複可能。',
		heighten: 'なし。',
	},
	{
		name: 'ウィッシュ',
		nameEn: 'Wish',
		rank: 9,
		traditions: ['秘術'],
		actions: 3,
		defense: '—',
		desc: '7ランク以下の任意の伝統の呪文を複製する。',
		heighten: 'なし。',
	},
	{
		name: 'フォアサイト',
		nameEn: 'Foresight',
		rank: 9,
		traditions: ['秘術', '神術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: 'AC・セーヴ・知覚に+2状況ボーナス。挟撃無効。1時間。',
		heighten: 'なし。',
	},
	{
		name: 'プリズマティック・ウォール',
		nameEn: 'Prismatic Wall',
		rank: 9,
		traditions: ['秘術', 'オカルト'],
		actions: 3,
		defense: '—',
		desc: '7色の壁。各色が異なる壊滅的な防御効果。通過に7回のセーヴ。',
		heighten: 'なし。',
	},
	{
		name: 'マサカー',
		nameEn: 'Massacre',
		rank: 9,
		traditions: ['秘術', '神術', '原始'],
		actions: 2,
		defense: '基本頑健',
		desc: '60ft直線の全敵にヴォイドダメージ。HP0以下は即死（蘇生困難）。',
		heighten: 'なし。',
	},
	{
		name: 'ストーム・オブ・ヴェンジャンス',
		nameEn: 'Storm of Vengeance',
		rank: 9,
		traditions: ['原始'],
		actions: 3,
		defense: '各種',
		desc: '400ft爆発の大嵐。毎ラウンド異なるダメージ。5ラウンド維持。',
		heighten: 'なし。',
	},

	// === ランク10 ===
	{
		name: 'タイムストップ',
		nameEn: 'Time Stop',
		rank: 10,
		traditions: ['秘術', 'オカルト'],
		actions: 3,
		defense: '—',
		desc: '時間を3ラウンド停止。その間自由に行動可能（他者に影響は制限）。',
		heighten: '—',
	},
	{
		name: 'ゲート',
		nameEn: 'Gate',
		rank: 10,
		traditions: ['秘術', '神術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '別の次元界への門を開く。クリーチャーの召喚にも使用可能。1分間維持。',
		heighten: '—',
	},
	{
		name: 'プライマル・フェノメノン',
		nameEn: 'Primal Phenomenon',
		rank: 10,
		traditions: ['原始'],
		actions: 3,
		defense: '—',
		desc: '自然界の法則を書き換える究極の原始呪文。7ランク以下の原始呪文を複製。',
		heighten: '—',
	},
	{
		name: 'リヴァイヴァル',
		nameEn: 'Revival',
		rank: 10,
		traditions: ['神術', '原始'],
		actions: 2,
		defense: '—',
		desc: '3日以内に死亡した最大5体を最大HPで蘇生。同じ戦闘中にも使用可能。',
		heighten: '—',
	},
	{
		name: 'ミラクル',
		nameEn: 'Miracle',
		rank: 10,
		traditions: ['神術'],
		actions: 3,
		defense: '—',
		desc: '神の奇跡。7ランク以下の任意の神術呪文を複製。GMの裁量で追加効果。',
		heighten: '—',
	},
	{
		name: 'プリズマティック・スフィア',
		nameEn: 'Prismatic Sphere',
		rank: 10,
		traditions: ['秘術', 'オカルト'],
		actions: 2,
		defense: '—',
		desc: '7色の防護球。入ろうとする者は7回のセーヴ。各色で壊滅的効果。',
		heighten: '—',
	},
];

// ─────────────────────────────────────
// 特技 (Feats) — 全クラス＋一般＋技能
// ─────────────────────────────────────
DB.feats = [
	// === ファイター ===
	{
		name: '猛突進',
		nameEn: 'Sudden Charge',
		level: 1,
		category: 'クラス',
		cls: 'ファイター',
		desc: '2アクション。2回Strideして打撃を1回行う。',
	},
	{
		name: 'パワーアタック',
		nameEn: 'Power Attack',
		level: 1,
		cls: 'ファイター',
		category: 'クラス',
		desc: '2アクション。武器のダメージダイスを追加して打撃（MAP増加あり）。',
	},
	{
		name: '反応的盾',
		nameEn: 'Reactive Shield',
		level: 1,
		cls: 'ファイター',
		category: 'クラス',
		desc: 'リアクションで盾を掲げ、1回の攻撃に対してACを向上。',
	},
	{
		name: '二刀流',
		nameEn: 'Double Slice',
		level: 1,
		cls: 'ファイター',
		category: 'クラス',
		desc: '2アクション。両手の武器で同時に攻撃（MAP軽減）。',
	},
	{
		name: '威圧打撃',
		nameEn: 'Intimidating Strike',
		level: 2,
		cls: 'ファイター',
		category: 'クラス',
		desc: '2アクション。打撃命中時に対象をデモラライズ（恐怖状態付与）。',
	},
	{
		name: '攻撃の機会',
		nameEn: 'Attack of Opportunity',
		level: 1,
		cls: 'ファイター',
		category: 'クラス',
		desc: 'リアクション。間合い内で誘発行動を取った敵に打撃。ファイターのみ1レベルで取得可能。',
	},
	{
		name: '戦闘柔軟性',
		nameEn: 'Combat Flexibility',
		level: 8,
		cls: 'ファイター',
		category: 'クラス',
		desc: '毎日の準備で8レベル以下のファイター特技を1つ選択して習得。',
	},
	{
		name: '決定的一撃',
		nameEn: 'Certain Strike',
		level: 10,
		cls: 'ファイター',
		category: 'クラス',
		desc: '打撃が外れた場合でも、武器ダメージ（ダイスを除く）を与える。',
	},
	{
		name: '恐怖の連撃',
		nameEn: 'Felling Strike',
		level: 12,
		cls: 'ファイター',
		category: 'クラス',
		desc: '2アクション。飛行中の敵に打撃。命中で落下させる。',
	},
	{
		name: 'デスペレートフィニッシャー',
		nameEn: 'Desperate Finisher',
		level: 14,
		cls: 'ファイター',
		category: 'クラス',
		desc: 'リアクション。ターン終了時に追加の打撃かプレス特技を使用可能。',
	},
	{
		name: '武器伝説',
		nameEn: 'Weapon Legend',
		level: 20,
		cls: 'ファイター',
		category: 'クラス',
		desc: '選択した武器グループが伝説級に。攻撃ロールにさらなるボーナス。',
	},

	// === ウィザード ===
	{
		name: '呪文延長',
		nameEn: 'Reach Spell',
		level: 1,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '+1アクション。接触呪文の射程を30ftに延長。',
	},
	{
		name: '呪文想起',
		nameEn: 'Spell Recall',
		level: 1,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '消費した呪文スロットを回復するための集中アクションを得る（マグス的）。',
	},
	{
		name: '結合アイテム',
		nameEn: 'Bonded Item',
		level: 1,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '1日1回、結合アイテムを使って消費した呪文スロットを1つ回復。',
	},
	{
		name: '呪文置換',
		nameEn: 'Spell Substitution',
		level: 1,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '10分間の集中で、準備済み呪文を呪文書の別の呪文に入れ替え。',
	},
	{
		name: '上級結合',
		nameEn: 'Superior Bond',
		level: 6,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '結合アイテムの使用回数が1日2回に増加。',
	},
	{
		name: '呪文貫通',
		nameEn: 'Spell Penetration',
		level: 10,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '呪文抵抗を持つ敵に対する対抗判定に+1状況ボーナス。',
	},
	{
		name: '効率的集中',
		nameEn: 'Effortless Concentration',
		level: 16,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '毎ターン開始時にフリーアクションで呪文を1つ維持。',
	},
	{
		name: 'スペルマスター',
		nameEn: 'Spell Combination',
		level: 20,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '2つの呪文を組み合わせて同時に唱える。',
	},
	{
		name: '反射呪文',
		nameEn: 'Reflect Spell',
		level: 14,
		cls: 'ウィザード',
		category: 'クラス',
		desc: '反呪文の成功時に呪文を術者に跳ね返す。',
	},

	// === クレリック ===
	{
		name: '治癒の手',
		nameEn: 'Healing Hands',
		level: 1,
		cls: 'クレリック',
		category: 'クラス',
		desc: 'ヒールの回復ダイスをd8からd10に増加。',
	},
	{
		name: '聖なるの防衛',
		nameEn: 'Holy Castigation',
		level: 1,
		cls: 'クレリック',
		category: 'クラス',
		desc: '悪の敵にヒールを使用した時、追加の善のダメージを与える。',
	},
	{
		name: '導きの力',
		nameEn: 'Channeled Succor',
		level: 4,
		cls: 'クレリック',
		category: 'クラス',
		desc: 'ヒール使用時に状態異常も同時に回復可能。',
	},
	{
		name: '多用途の詠唱',
		nameEn: 'Versatile Font',
		level: 2,
		cls: 'クレリック',
		category: 'クラス',
		desc: 'ヒールとハームの両方の追加スロットを得る（通常はどちらか一方）。',
	},
	{
		name: '選択的エネルギー',
		nameEn: 'Selective Energy',
		level: 6,
		cls: 'クレリック',
		category: 'クラス',
		desc: '3アクションのヒール/ハーム使用時に味方を効果から除外可能。',
	},
	{
		name: '神の介入',
		nameEn: 'Divine Intervention',
		level: 18,
		cls: 'クレリック',
		category: 'クラス',
		desc: '1日1回。10ランク相当の神術効果を発動。',
	},
	{
		name: '聖なる盾',
		nameEn: 'Emblazon Armament',
		level: 2,
		cls: 'クレリック',
		category: 'クラス',
		desc: '盾か武器に神聖なシンボルを刻み、追加効果を付与。',
	},
	{
		name: '上級導き',
		nameEn: 'Advanced Domain',
		level: 8,
		cls: 'クレリック',
		category: 'クラス',
		desc: '上級領域呪文を習得。集中プールも拡大。',
	},

	// === バード ===
	{
		name: '勇壮なる歌',
		nameEn: 'Courageous Anthem',
		level: 1,
		cls: 'バード',
		category: 'クラス',
		desc: '集中キャントリップ。30ft放射内の味方に攻撃ロール+1状況ボーナス。',
	},
	{
		name: '鎮魂歌',
		nameEn: 'Dirge of Doom',
		level: 6,
		cls: 'バード',
		category: 'クラス',
		desc: '集中キャントリップ。30ft放射内の敵に恐怖1（セーヴなし）。',
	},
	{
		name: 'リンガリング・コンポジション',
		nameEn: 'Lingering Composition',
		level: 1,
		cls: 'バード',
		category: 'クラス',
		desc: '演奏の効果持続を延長（3ラウンドまたは4ラウンド）。',
	},
	{
		name: 'マルチジャンル人',
		nameEn: 'Versatile Performance',
		level: 1,
		cls: 'バード',
		category: 'クラス',
		desc: '芸能判定を外交・威圧・欺瞞の代わりに使用可能。',
	},
	{
		name: '聴衆を魅了',
		nameEn: 'Captivating Adoration',
		level: 4,
		cls: 'バード',
		category: 'クラス',
		desc: '演奏聴取中の生物をあなたに対して友好的にする。',
	},
	{
		name: '不可思議な呪文',
		nameEn: 'Unusual Composition',
		level: 2,
		cls: 'バード',
		category: 'クラス',
		desc: '呪文の構成要素を変更し、音声/動作の制限を回避。',
	},

	// === ローグ ===
	{
		name: '急所攻撃',
		nameEn: 'Sneak Attack',
		level: 1,
		cls: 'ローグ',
		category: 'クラス',
		desc: '（自動取得）挟撃等で不意を突いた敵に追加精密ダメージ。',
	},
	{
		name: '機動的回避',
		nameEn: 'Nimble Dodge',
		level: 1,
		cls: 'ローグ',
		category: 'クラス',
		desc: 'リアクションでACに+2状況ボーナス（1回の攻撃）。',
	},
	{
		name: '罠発見',
		nameEn: 'Trap Finder',
		level: 1,
		cls: 'ローグ',
		category: 'クラス',
		desc: '罠の発見に+1状況ボーナス。罠の回避にもボーナス。',
	},
	{
		name: '衰弱打撃',
		nameEn: 'Debilitating Strike',
		level: 10,
		cls: 'ローグ',
		category: 'クラス',
		desc: '急所攻撃命中時に移動速度半減かAC-2を付与。',
	},
	{
		name: '達人の一撃',
		nameEn: 'Master Strike',
		level: 14,
		cls: 'ローグ',
		category: 'クラス',
		desc: '急所攻撃命中時に頑健セーヴを強制。失敗で追加の壊滅的効果。',
	},
	{
		name: '二重衰弱',
		nameEn: 'Double Debilitation',
		level: 12,
		cls: 'ローグ',
		category: 'クラス',
		desc: '衰弱打撃で2つの効果を同時に付与可能。',
	},
	{
		name: '暗殺',
		nameEn: 'Assassinate',
		level: 18,
		cls: 'ローグ',
		category: 'クラス',
		desc: '隠密からの打撃で即死効果（頑健セーヴ）。',
	},

	// === レンジャー ===
	{
		name: '獲物の指定',
		nameEn: 'Hunt Prey',
		level: 1,
		cls: 'レンジャー',
		category: 'クラス',
		desc: '（自動取得）対象を獲物に指定。追跡・攻撃にボーナス。',
	},
	{
		name: '双撃',
		nameEn: 'Twin Takedown',
		level: 1,
		cls: 'レンジャー',
		category: 'クラス',
		desc: '二刀流で獲物に2回攻撃。1アクション。',
	},
	{
		name: '動物の仲間',
		nameEn: 'Animal Companion',
		level: 1,
		cls: 'レンジャー',
		category: 'クラス',
		desc: '動物の仲間を1体得る。指示に1アクション消費。',
	},
	{
		name: '怪物殺し',
		nameEn: 'Monster Hunter',
		level: 1,
		cls: 'レンジャー',
		category: 'クラス',
		desc: 'リコール・ナレッジ成功時に獲物への攻撃に+1状況ボーナス。',
	},

	// === モンク ===
	{
		name: '連打',
		nameEn: 'Flurry of Blows',
		level: 1,
		cls: 'モンク',
		category: 'クラス',
		desc: '（自動取得）1アクションで素手攻撃を2回行う。',
	},
	{
		name: '鶴の構え',
		nameEn: 'Crane Stance',
		level: 1,
		cls: 'モンク',
		category: 'クラス',
		desc: '特殊な構え。ACに+1状況ボーナス。鶴の翼攻撃（1d6殴打）を使用可能。',
	},
	{
		name: '気功爆発',
		nameEn: 'Ki Blast',
		level: 6,
		cls: 'モンク',
		category: 'クラス',
		desc: '集中呪文。力場ダメージの爆発か直線攻撃を放つ。',
	},
	{
		name: '疾風歩法',
		nameEn: 'Wind Jump',
		level: 6,
		cls: 'モンク',
		category: 'クラス',
		desc: '集中呪文。跳躍距離を大幅に延長。垂直方向にも跳躍可能。',
	},
	{
		name: '完全な打撃',
		nameEn: 'Stunning Fist',
		level: 2,
		cls: 'モンク',
		category: 'クラス',
		desc: '連打で敵にクリティカルヒット時に朦朧状態を付与。',
	},

	// === チャンピオン ===
	{
		name: '信仰の領域',
		nameEn: "Deity's Domain",
		level: 1,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '信仰する神格の領域呪文を習得。集中呪文として使用可能。',
	},
	{
		name: '遠隔報復',
		nameEn: 'Ranged Reprisal',
		level: 1,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '報復の一撃をリーチ外の敵にも使用可能にする。',
	},
	{
		name: '神の恩寵',
		nameEn: 'Divine Grace',
		level: 2,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: 'リアクション。セーヴィングスローに+2状況ボーナス。',
	},
	{
		name: '勇気のオーラ',
		nameEn: 'Aura of Courage',
		level: 4,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '15ft以内の味方は恐怖1に対して免疫。',
	},
	{
		name: '慈悲',
		nameEn: 'Mercy',
		level: 4,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: 'レイ・オン・ハンズ使用時に麻痺や恐怖状態を除去。',
	},
	{
		name: '機会攻撃',
		nameEn: 'Attack of Opportunity',
		level: 6,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '間合い内で誘発行動を取った敵にリアクションで打撃。',
	},
	{
		name: '邪悪破壊',
		nameEn: 'Smite Evil',
		level: 6,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '1アクションで指定した敵への打撃に追加ダメージ。',
	},
	{
		name: '盾の護り',
		nameEn: 'Shield Warden',
		level: 6,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '隣接味方への攻撃にも盾ブロックを使用可能。',
	},
	{
		name: '高速盾',
		nameEn: 'Quick Block',
		level: 8,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '盾ブロック専用の追加リアクションを得る。',
	},
	{
		name: '上級慈悲',
		nameEn: 'Advanced Mercy',
		level: 8,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: 'レイ・オン・ハンズで盲目・減速も除去可能に。',
	},
	{
		name: '献身集中',
		nameEn: 'Devoted Focus',
		level: 10,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '再集中時に集中ポイントを2点回復。',
	},
	{
		name: '盾の圧倒',
		nameEn: 'Shield of Reckoning',
		level: 12,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: '盾ブロックとチャンピオンの反応を同時使用。',
	},
	{
		name: '究極の慈悲',
		nameEn: 'Ultimate Mercy',
		level: 18,
		cls: 'チャンピオン',
		category: 'クラス',
		desc: 'レイ・オン・ハンズで死亡した味方を蘇生（1日1回）。',
	},

	// === ドルイド ===
	{
		name: '動物の相棒',
		nameEn: 'Animal Companion',
		level: 1,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '動物の仲間を1体得る。指示に1アクション消費。',
	},
	{
		name: '野生変身',
		nameEn: 'Wild Shape',
		level: 1,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '集中呪文として動物の姿に変身。',
	},
	{
		name: '呪文拡大',
		nameEn: 'Widen Spell',
		level: 1,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '+1アクション。範囲呪文の範囲を拡大。',
	},
	{
		name: '形態制御',
		nameEn: 'Form Control',
		level: 4,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '野生変身の持続時間を1時間に延長（2ランク低い呪文として扱う）。',
	},
	{
		name: '成熟した動物の仲間',
		nameEn: 'Mature Animal Companion',
		level: 4,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '動物の仲間を成熟させ強化。',
	},
	{
		name: '昆虫の姿',
		nameEn: 'Insect Shape',
		level: 6,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '昆虫の姿に変身可能。飛行形態も含む。',
	},
	{
		name: '獰猛な形態',
		nameEn: 'Ferocious Shape',
		level: 8,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '野生変身中の攻撃に追加ダメージ。致命的効果も付与。',
	},
	{
		name: '飛翔の姿',
		nameEn: 'Soaring Shape',
		level: 8,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '空中の形態への変身が可能に。',
	},
	{
		name: '元素の姿',
		nameEn: 'Elemental Shape',
		level: 10,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '火・水・地・風の元素の姿に変身可能。',
	},
	{
		name: '竜の姿',
		nameEn: 'Dragon Shape',
		level: 12,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '竜に変身。ブレス攻撃と飛行能力を得る。',
	},
	{
		name: '効率的集中',
		nameEn: 'Effortless Concentration',
		level: 16,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '毎ターン開始時にフリーアクションで呪文を1つ維持。',
	},
	{
		name: '完全形態制御',
		nameEn: 'Perfect Form Control',
		level: 18,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '最高ランクで野生変身を維持しつつ持続時間延長。',
	},
	{
		name: '真の変身者',
		nameEn: 'True Shapeshifter',
		level: 20,
		cls: 'ドルイド',
		category: 'クラス',
		desc: '2つの変身を同時維持・切り替え可能。無限持続。',
	},

	// === ソーサラー ===
	{
		name: '危険な魔術',
		nameEn: 'Dangerous Sorcery',
		level: 1,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: 'ダメージ呪文に呪文ランクと同値の追加ダメージ。',
	},
	{
		name: '呪文拡大',
		nameEn: 'Widen Spell',
		level: 1,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '+1アクション。範囲呪文の範囲を拡大。',
	},
	{
		name: '反呪文',
		nameEn: 'Counterspell',
		level: 1,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: 'リアクションで同じ呪文を消費して相手の呪文を打ち消す。',
	},
	{
		name: '上級血脈',
		nameEn: 'Advanced Bloodline',
		level: 6,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '血脈の上級集中呪文を習得。集中プール拡大。',
	},
	{
		name: '圧倒的エネルギー',
		nameEn: 'Overwhelming Energy',
		level: 10,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '元素ダメージ呪文がダメージ抵抗を無視する。',
	},
	{
		name: '高速詠唱',
		nameEn: 'Quickened Casting',
		level: 10,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '1日1回、フリーアクションで追加の呪文を唱えられる。',
	},
	{
		name: '血脈集中',
		nameEn: 'Bloodline Focus',
		level: 12,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '再集中で集中ポイントを2点回復。',
	},
	{
		name: '効率的集中',
		nameEn: 'Effortless Concentration',
		level: 16,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '毎ターンフリーアクションで呪文を1つ維持。',
	},
	{
		name: '血脈導体',
		nameEn: 'Bloodline Conduit',
		level: 20,
		cls: 'ソーサラー',
		category: 'クラス',
		desc: '5ランク以下の呪文を毎分スロット消費なしで唱えられる。',
	},

	// === バーバリアン ===
	{
		name: '猛突進',
		nameEn: 'Sudden Charge',
		level: 1,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: '2アクション。2回移動して打撃を1回。',
	},
	{
		name: '激怒の威圧',
		nameEn: 'Raging Intimidation',
		level: 1,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: '激怒中に威圧使用可能。威圧特技の前提条件を無視。',
	},
	{
		name: '恐怖の咆哮',
		nameEn: 'Terrifying Howl',
		level: 6,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: '30ft以内の全敵をデモラライズ。',
	},
	{
		name: '竜の激怒',
		nameEn: "Dragon's Rage Breath",
		level: 6,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: '（竜の本能）ブレス攻撃を放つ。',
	},
	{
		name: '無鉄砲放棄',
		nameEn: 'Reckless Abandon',
		level: 10,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: 'ACを犠牲に一時HPとダメージボーナスを得る。',
	},
	{
		name: '不屈の激怒',
		nameEn: 'Undying Ferocity',
		level: 12,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: 'HP0でも倒れず、一時HP獲得で戦闘継続。',
	},
	{
		name: '猛威の化身',
		nameEn: 'Contagious Rage',
		level: 20,
		cls: 'バーバリアン',
		category: 'クラス',
		desc: '味方にも激怒の効果を付与可能。',
	},

	// === アルケミスト ===
	{
		name: '素早い爆弾',
		nameEn: 'Quick Bomber',
		level: 1,
		cls: 'アルケミスト',
		category: 'クラス',
		desc: '1アクションで爆弾を取り出して投擲。',
	},
	{
		name: '粘液爆弾',
		nameEn: 'Sticky Bomb',
		level: 6,
		cls: 'アルケミスト',
		category: 'クラス',
		desc: '爆弾を粘着性にし飛散ダメージ持続。',
	},
	{
		name: '広域爆撃',
		nameEn: 'Expanded Splash',
		level: 8,
		cls: 'アルケミスト',
		category: 'クラス',
		desc: '飛散ダメージの範囲と量を増加。',
	},
	{
		name: '二重霊薬',
		nameEn: 'Double Elixir',
		level: 10,
		cls: 'アルケミスト',
		category: 'クラス',
		desc: '一度に同じエリクサーを2個作成。',
	},
	{
		name: '永久エリクサー',
		nameEn: 'Eternal Elixir',
		level: 16,
		cls: 'アルケミスト',
		category: 'クラス',
		desc: '特定のエリクサーの効果を永続化（1個まで）。',
	},

	// === ウィッチ ===
	{
		name: 'カックル',
		nameEn: 'Cackle',
		level: 1,
		cls: 'ウィッチ',
		category: 'クラス',
		desc: 'フリーアクションで集中呪文を維持。',
	},
	{
		name: '使い魔強化',
		nameEn: 'Enhanced Familiar',
		level: 2,
		cls: 'ウィッチ',
		category: 'クラス',
		desc: '使い魔の能力選択数を2つ増加。',
	},
	{
		name: '生けるヘアー',
		nameEn: 'Living Hair',
		level: 4,
		cls: 'ウィッチ',
		category: 'クラス',
		desc: '髪を素手攻撃武器として使用可能。',
	},
	{
		name: 'パトロンの贈り物',
		nameEn: "Patron's Gift",
		level: 8,
		cls: 'ウィッチ',
		category: 'クラス',
		desc: '追加の集中呪文を習得。集中プール拡大。',
	},
	{
		name: '大いなる呪い',
		nameEn: 'Grand Hex',
		level: 18,
		cls: 'ウィッチ',
		category: 'クラス',
		desc: 'ヘックスの効果範囲と持続時間が大幅拡張。',
	},

	// === スワッシュバックラー ===
	{
		name: 'みんなのために',
		nameEn: 'One for All',
		level: 1,
		cls: 'スワッシュバックラー',
		category: 'クラス',
		desc: '外交判定で味方を援護。成功で+2状況ボーナス。',
	},
	{
		name: '自信のフィニッシュ',
		nameEn: 'Confident Finisher',
		level: 1,
		cls: 'スワッシュバックラー',
		category: 'クラス',
		desc: '鍛冶場消費のフィニッシュ。外れても半ダメージ。',
	},
	{
		name: '身交わし',
		nameEn: 'Nimble Dodge',
		level: 1,
		cls: 'スワッシュバックラー',
		category: 'クラス',
		desc: 'リアクションでACに+2状況ボーナス。',
	},
	{
		name: '致命的フィニッシュ',
		nameEn: 'Lethal Finisher',
		level: 10,
		cls: 'スワッシュバックラー',
		category: 'クラス',
		desc: '2アクション。致死的なダメージのフィニッシュ。',
	},
	{
		name: '永遠の鍛冶場',
		nameEn: 'Eternal Confidence',
		level: 18,
		cls: 'スワッシュバックラー',
		category: 'クラス',
		desc: '鍛冶場の管理不要。常にフィニッシュ使用可能。',
	},

	// === インヴェスティゲーター ===
	{
		name: '手がかり探し',
		nameEn: 'Pursue a Lead',
		level: 1,
		cls: 'インヴェスティゲーター',
		category: 'クラス',
		desc: '（自動取得）手がかりを追跡。関連判定にボーナス。',
	},
	{
		name: '戦略的一撃',
		nameEn: 'Strategic Strike',
		level: 1,
		cls: 'インヴェスティゲーター',
		category: 'クラス',
		desc: '（自動取得）手がかりに関連した敵への打撃に追加精密ダメージ。',
	},
	// === インヴェスティゲーター（続き） ===
	{
		name: '証拠収集者',
		nameEn: 'Clue In',
		level: 2,
		cls: 'インヴェスティゲーター',
		category: 'クラス',
		desc: 'リアクション。味方にリコール・ナレッジの結果を共有。',
	},
	{
		name: '推理の連鎖',
		nameEn: 'Devise a Stratagem',
		level: 1,
		cls: 'インヴェスティゲーター',
		category: 'クラス',
		desc: '攻撃前にd20を振り、結果を見てから攻撃するか決定できる。',
	},
	{
		name: '鋭い観察眼',
		nameEn: 'Keen Recollection',
		level: 8,
		cls: 'インヴェスティゲーター',
		category: 'クラス',
		desc: 'リコール・ナレッジの大失敗が通常の失敗になる。',
	},
	{
		name: '推理の達人',
		nameEn: 'Master Spotter',
		level: 14,
		cls: 'インヴェスティゲーター',
		category: 'クラス',
		desc: '隠れた敵や罠の探知にマスターレベルのボーナス。',
	},

	// === オラクル ===
	{
		name: '呪いの啓示',
		nameEn: 'Cursebound Revelation',
		level: 1,
		cls: 'オラクル',
		category: 'クラス',
		desc: '集中呪文使用時に呪いが深まり、追加効果を得る。',
	},
	{
		name: '神秘の領域',
		nameEn: 'Domain Acumen',
		level: 1,
		cls: 'オラクル',
		category: 'クラス',
		desc: '神秘に関連する領域呪文を1つ習得。',
	},
	{
		name: '呪いの制御',
		nameEn: 'Moderate Curse',
		level: 6,
		cls: 'オラクル',
		category: 'クラス',
		desc: '呪いの中度段階でも戦闘を維持可能に。ペナルティ軽減。',
	},
	{
		name: '上級啓示',
		nameEn: 'Greater Revelation',
		level: 10,
		cls: 'オラクル',
		category: 'クラス',
		desc: 'より強力な集中呪文を習得。集中プール拡大。',
	},
	{
		name: '究極の呪い',
		nameEn: 'Extreme Curse',
		level: 18,
		cls: 'オラクル',
		category: 'クラス',
		desc: '呪いの最終段階を解放。壊滅的だが圧倒的な力を得る。',
	},

	// === ガンスリンガー ===
	{
		name: 'カバーファイア',
		nameEn: 'Cover Fire',
		level: 1,
		cls: 'ガンスリンガー',
		category: 'クラス',
		desc: '射撃で援護。味方にACへの+1状況ボーナスまたは敵に恐怖1。',
	},
	{
		name: '致命的射撃',
		nameEn: 'Fatal Shot',
		level: 1,
		cls: 'ガンスリンガー',
		category: 'クラス',
		desc: 'リロード後の最初の射撃にダメージボーナス。',
	},
	{
		name: '散弾射撃',
		nameEn: 'Scatter Blast',
		level: 6,
		cls: 'ガンスリンガー',
		category: 'クラス',
		desc: '散弾銃で円錐範囲の攻撃。複数の敵にダメージ。',
	},
	{
		name: '連射',
		nameEn: 'Running Reload',
		level: 4,
		cls: 'ガンスリンガー',
		category: 'クラス',
		desc: '移動しながらリロードを行う。1アクションで移動+リロード。',
	},
	{
		name: '貫通弾',
		nameEn: 'Penetrating Fire',
		level: 10,
		cls: 'ガンスリンガー',
		category: 'クラス',
		desc: '射撃が1体目を貫通し、直線上の2体目にも命中。',
	},
	{
		name: '伝説の射手',
		nameEn: 'Unerring Shot',
		level: 18,
		cls: 'ガンスリンガー',
		category: 'クラス',
		desc: '遮蔽を完全に無視して射撃可能。',
	},

	// === インヴェンター ===
	{
		name: '改造（武器）',
		nameEn: 'Innovation (Weapon)',
		level: 1,
		cls: 'インヴェンター',
		category: 'クラス',
		desc: '（自動取得）武器に革新的な改造を施す。特殊な追加効果を選択。',
	},
	{
		name: '改造（防具）',
		nameEn: 'Innovation (Armor)',
		level: 1,
		cls: 'インヴェンター',
		category: 'クラス',
		desc: '（自動取得）防具に革新的な改造。速度ボーナスや抵抗を選択。',
	},
	{
		name: '改造（コンストラクト）',
		nameEn: 'Innovation (Construct)',
		level: 1,
		cls: 'インヴェンター',
		category: 'クラス',
		desc: '（自動取得）コンストラクトの仲間を作成。命令で戦闘参加。',
	},
	{
		name: '爆発的跳躍',
		nameEn: 'Explosive Leap',
		level: 4,
		cls: 'インヴェンター',
		category: 'クラス',
		desc: '爆発で大ジャンプ。着地点周囲にダメージ。',
	},
	{
		name: 'メガトンストライク',
		nameEn: 'Megaton Strike',
		level: 8,
		cls: 'インヴェンター',
		category: 'クラス',
		desc: '2アクションの強力な打撃。追加ダメージダイスと押しのけ効果。',
	},
	{
		name: '不安定の天才',
		nameEn: 'Unstable Genius',
		level: 10,
		cls: 'インヴェンター',
		category: 'クラス',
		desc: '不安定な改造で通常以上の効果を発揮（失敗リスクあり）。',
	},

	// === マグス ===
	{
		name: 'スペルストライク',
		nameEn: 'Spellstrike',
		level: 1,
		cls: 'マグス',
		category: 'クラス',
		desc: '（自動取得）呪文を打撃に乗せる。2アクションで攻撃と呪文を同時発動。',
	},
	{
		name: '秘術カスケード',
		nameEn: 'Arcane Cascade',
		level: 1,
		cls: 'マグス',
		category: 'クラス',
		desc: '呪文詠唱後に構えを取り、打撃に追加ダメージ（呪文の属性）。',
	},
	{
		name: '反射スペルストライク',
		nameEn: 'Cascading Ray',
		level: 6,
		cls: 'マグス',
		category: 'クラス',
		desc: 'スペルストライクの余剰効果が近くの敵にも波及。',
	},
	{
		name: '二重スペルストライク',
		nameEn: 'Standby Spell',
		level: 10,
		cls: 'マグス',
		category: 'クラス',
		desc: 'スペルストライク再チャージ時に別の呪文を待機させられる。',
	},
	{
		name: '究極スペルストライク',
		nameEn: 'Supreme Spellstrike',
		level: 18,
		cls: 'マグス',
		category: 'クラス',
		desc: 'スペルストライクの再チャージが大幅に高速化。',
	},

	// === キネティシスト ===
	{
		name: '元素の爆発',
		nameEn: 'Elemental Blast',
		level: 1,
		cls: 'キネティシスト',
		category: 'クラス',
		desc: '（自動取得）選択した元素で攻撃。近接または遠隔。',
	},
	{
		name: '元素の防御',
		nameEn: 'Elemental Defense',
		level: 1,
		cls: 'キネティシスト',
		category: 'クラス',
		desc: '元素の力でACまたはセーヴにボーナスを得る。',
	},
	{
		name: 'オーバーフロー',
		nameEn: 'Overflow',
		level: 1,
		cls: 'キネティシスト',
		category: 'クラス',
		desc: '元素の力を過剰放出し、強力な範囲攻撃を行う。',
	},
	{
		name: '複合元素',
		nameEn: 'Dual Gate',
		level: 6,
		cls: 'キネティシスト',
		category: 'クラス',
		desc: '2つの元素を同時に操作可能。複合効果の攻撃が解禁。',
	},
	{
		name: '元素奔流',
		nameEn: 'Channel Elements',
		level: 1,
		cls: 'キネティシスト',
		category: 'クラス',
		desc: '（自動取得）元素の力を集めてオーラやインパルスを起動。',
	},
	{
		name: '元素嵐',
		nameEn: 'Elemental Tempest',
		level: 14,
		cls: 'キネティシスト',
		category: 'クラス',
		desc: '大規模な元素の嵐を発生させ、広範囲にダメージ。',
	},

	// === 一般特技 ===
	{
		name: 'タフネス',
		nameEn: 'Toughness',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: '最大HPがレベル分増加。瀕死回復判定にも+1。',
	},
	{
		name: '驚異的イニシアチブ',
		nameEn: 'Incredible Initiative',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: 'イニシアチブ判定に+2状況ボーナス。',
	},
	{
		name: '防具習熟',
		nameEn: 'Armor Proficiency',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: '次の段階の防具（軽装→中装→重装）の訓練を得る。',
	},
	{
		name: '鑑定眼',
		nameEn: 'Canny Acumen',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: '頑健/反応/意志/知覚のいずれか1つの習熟を上級者に引き上げる（17レベルで達人に）。',
	},
	{
		name: 'シールドブロック',
		nameEn: 'Shield Block',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: 'リアクション。盾の硬度分のダメージを軽減（盾もダメージを受ける）。',
	},
	{
		name: '迅速な回復',
		nameEn: 'Fast Recovery',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: '休息時の回復量が倍増。病気や毒の回復判定にもボーナス。',
	},
	{
		name: '追加HP',
		nameEn: 'Diehard',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: '瀕死状態の最大値が4から5に増加。死亡しにくくなる。',
	},
	{
		name: 'フリート',
		nameEn: 'Fleet',
		level: 1,
		category: '一般',
		cls: '全クラス',
		desc: '移動速度が+5フィート。',
	},
	{
		name: '自然な曖昧さ',
		nameEn: 'Untrained Improvisation',
		level: 3,
		category: '一般',
		cls: '全クラス',
		desc: '未訓練の技能判定にレベルの半分をボーナスとして加算（7レベルで全額）。',
	},
	{
		name: '祖先の遺産',
		nameEn: 'Ancestral Paragon',
		level: 3,
		category: '一般',
		cls: '全クラス',
		desc: '1レベルの祖先特技を1つ追加で習得。',
	},

	// === 技能特技 ===
	{
		name: '戦場医療',
		nameEn: 'Battle Medicine',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '医術',
		desc: '1アクション。戦闘中に傷の手当て。対象1体を回復（1日1回/対象）。',
	},
	{
		name: '確実な知識',
		nameEn: 'Assurance',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '任意',
		desc: '選択した技能で10+習熟ボーナスを自動的な判定結果にできる。',
	},
	{
		name: '威嚇の視線',
		nameEn: 'Intimidating Glare',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '威圧',
		desc: 'デモラライズから聴覚要素を除去。言語が通じない相手も威圧可能。',
	},
	{
		name: '嘘看破',
		nameEn: 'Lie to Me',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '欺瞞',
		desc: '欺瞞DCで嘘を看破。知覚の代わりに使用可能。',
	},
	{
		name: '印象操作',
		nameEn: 'Charming Liar',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '欺瞞',
		desc: '嘘が見破られなかった場合、態度を友好的にする。',
	},
	{
		name: '猫落下',
		nameEn: 'Cat Fall',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '軽業',
		desc: '落下ダメージを軽減。習熟に応じて軽減量が増加。',
	},
	{
		name: '迅速な修理',
		nameEn: 'Quick Repair',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '製作',
		desc: '修理にかかる時間を大幅短縮（1アクション/1分間）。',
	},
	{
		name: '呪文識別',
		nameEn: 'Recognize Spell',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '神秘学/自然/オカルト/宗教',
		desc: 'リアクション。唱えられている呪文を識別。',
	},
	{
		name: 'ボンモ',
		nameEn: 'Bon Mot',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '外交',
		desc: '1アクション。機知に富んだ言葉で敵の意志セーヴに-2〜-3ペナルティ。',
	},
	{
		name: '戦の叫び',
		nameEn: 'Battlecry',
		level: 7,
		category: '技能',
		cls: '全クラス',
		skill: '威圧',
		desc: 'イニシアチブロール時にフリーアクションでデモラライズを行う。',
	},
	{
		name: '致死の恐怖',
		nameEn: 'Scare to Death',
		level: 15,
		category: '技能',
		cls: '全クラス',
		skill: '威圧',
		desc: '1アクション。対象の意志セーヴ失敗で恐怖4、大失敗で即死。',
	},
	{
		name: '伝説の交渉',
		nameEn: 'Legendary Negotiation',
		level: 15,
		category: '技能',
		cls: '全クラス',
		skill: '外交',
		desc: '3アクション。敵との交渉を即座に試みる（24時間の休戦）。',
	},
	{
		name: '素早い飛び出し',
		nameEn: 'Quick Jump',
		level: 1,
		category: '技能',
		cls: '全クラス',
		skill: '運動',
		desc: '跳躍を1アクションで実行可能。助走不要。',
	},
];

// ─────────────────────────────────────
// 装備 (Equipment)
// ─────────────────────────────────────
DB.weapons = [
	{
		name: 'ロングソード',
		nameEn: 'Longsword',
		category: '武器（片手近接）',
		damage: '1d8斬撃',
		price: '1gp',
		traits: ['多用途 d10'],
		desc: '最も一般的な片手剣。両手持ちでd10に増加。',
	},
	{
		name: 'グレートソード',
		nameEn: 'Greatsword',
		category: '武器（両手近接）',
		damage: '1d12斬撃',
		price: '2gp',
		traits: ['多用途 P'],
		desc: '大型の両手剣。刺突に切り替え可能。',
	},
	{
		name: 'ロングボウ',
		nameEn: 'Longbow',
		category: '武器（両手遠隔）',
		damage: '1d8刺突',
		price: '6gp',
		traits: ['致命d10', '射程100ft', '装填0'],
		desc: '長距離の弓。射程と精度に優れる。',
	},
	{
		name: 'レイピア',
		nameEn: 'Rapier',
		category: '武器（片手近接）',
		damage: '1d6刺突',
		price: '2gp',
		traits: ['致命d8', '巧技', '離脱'],
		desc: '技巧派の剣。DEXで攻撃可能。離脱特性持ち。',
	},
	{
		name: 'ウォーハンマー',
		nameEn: 'Warhammer',
		category: '武器（片手近接）',
		damage: '1d8殴打',
		price: '1gp',
		traits: ['押しのけ'],
		desc: '頑強な打撃武器。クリティカルで5ft押しのけ。',
	},
	{
		name: 'ショートボウ',
		nameEn: 'Shortbow',
		category: '武器（両手遠隔）',
		damage: '1d6刺突',
		price: '3gp',
		traits: ['致命d10', '射程60ft', '装填0'],
		desc: '小型の弓。取り回しがよい。',
	},
	{
		name: 'ダガー',
		nameEn: 'Dagger',
		category: '武器（片手近接）',
		damage: '1d4刺突',
		price: '2sp',
		traits: ['敏捷', '巧技', '投擲10ft', '多用途S'],
		desc: '万能の小型武器。投擲可能。',
	},
	{
		name: 'ジャヴェリン',
		nameEn: 'Javelin',
		category: '武器（遠隔）',
		damage: '1d6刺突',
		price: '1sp',
		traits: ['投擲30ft'],
		desc: '投げ槍。安価で使い捨てに適する。',
	},
	{
		name: 'グレートアックス',
		nameEn: 'Greataxe',
		category: '武器（両手近接）',
		damage: '1d12斬撃',
		price: '2gp',
		traits: ['掃討'],
		desc: '大型の斧。クリティカル時にダメージダイス追加。',
	},
	{
		name: 'フレイル',
		nameEn: 'Flail',
		category: '武器（片手近接）',
		damage: '1d6殴打',
		price: '8sp',
		traits: ['離脱', '掃討', '足払い'],
		desc: '鎖分銅。足払い特性持ち。',
	},
	{
		name: 'スタッフ',
		nameEn: 'Staff',
		category: '武器（両手近接）',
		damage: '1d4殴打',
		price: '0',
		traits: ['両手d8'],
		desc: '杖。単純武器。両手持ちでd8に増加。',
	},
	{
		name: 'クロスボウ',
		nameEn: 'Crossbow',
		category: '武器（両手遠隔）',
		damage: '1d8刺突',
		price: '3gp',
		traits: ['射程120ft', '装填1'],
		desc: '弩。射程は長いがリロードに1アクション。',
	},
];

DB.armor = [
	{
		name: 'レザーアーマー',
		nameEn: 'Leather Armor',
		category: '軽装鎧',
		ac: 1,
		dexCap: 4,
		price: '2gp',
		traits: [],
		desc: '柔軟な革の鎧。判定ペナルティ-1。',
	},
	{
		name: 'スタデッドレザー',
		nameEn: 'Studded Leather',
		category: '軽装鎧',
		ac: 2,
		dexCap: 3,
		price: '3gp',
		traits: [],
		desc: '鋲打ちの革鎧。判定ペナルティ-1。',
	},
	{
		name: 'チェインメイル',
		nameEn: 'Chain Mail',
		category: '中装鎧',
		ac: 4,
		dexCap: 1,
		price: '6gp',
		traits: ['柔軟', '騒音'],
		desc: '鎖帷子。柔軟だがやや重い。判定ペナルティ-2。速度-5ft。',
	},
	{
		name: 'ブレストプレート',
		nameEn: 'Breastplate',
		category: '中装鎧',
		ac: 4,
		dexCap: 1,
		price: '8gp',
		traits: [],
		desc: '胸甲。バランスの良い中装鎧。判定ペナルティ-2。速度-5ft。',
	},
	{
		name: 'ハイドアーマー',
		nameEn: 'Hide Armor',
		category: '中装鎧',
		ac: 3,
		dexCap: 2,
		price: '2gp',
		traits: [],
		desc: '獣皮の鎧。ドルイドも使用可能（非金属）。判定ペナルティ-2。速度-5ft。',
	},
	{
		name: 'フルプレート',
		nameEn: 'Full Plate',
		category: '重装鎧',
		ac: 6,
		dexCap: 0,
		price: '30gp',
		traits: ['防壁'],
		desc: '全身鎧。最高のAC。防壁で反応セーヴにDEXの代わりに+3。判定ペナルティ-3。速度-10ft。',
	},
	{
		name: 'ハーフプレート',
		nameEn: 'Half Plate',
		category: '重装鎧',
		ac: 5,
		dexCap: 1,
		price: '18gp',
		traits: [],
		desc: '半身鎧。重装の中では動きやすい。判定ペナルティ-3。速度-10ft。',
	},
	{
		name: 'エクスプローラーズ・クロージング',
		nameEn: "Explorer's Clothing",
		category: '非防具',
		ac: 0,
		dexCap: 5,
		price: '1sp',
		traits: ['快適'],
		desc: '冒険者の衣服。ルーンを刻める。ACボーナスなし。',
	},
];

DB.adventuringGear = [
	{
		name: '冒険者キット',
		nameEn: "Adventurer's Kit",
		price: '7sp',
		desc: 'バックパック、寝袋、火打ち石、ロープ50ft、松明10本、保存食14日分、水袋。',
	},
	{
		name: '治療具',
		nameEn: "Healer's Kit",
		price: '5gp',
		desc: '傷の手当て（医術技能）に必要。10回分の使用。',
	},
	{
		name: '盗賊道具',
		nameEn: "Thieves' Tools",
		price: '3gp',
		desc: '開錠・罠解除（窃盗技能）に必要。',
	},
	{
		name: '聖印',
		nameEn: 'Religious Symbol',
		price: '2gp',
		desc: '信仰する神格の聖印。神術の呪文構成要素として使用。',
	},
	{
		name: '呪文構成要素嚢',
		nameEn: 'Material Component Pouch',
		price: '5sp',
		desc: '呪文の物質要素を入れる小袋。',
	},
	{
		name: '錬金術道具',
		nameEn: "Alchemist's Tools",
		price: '3gp',
		desc: '錬金術アイテムの作成に必要な道具一式。',
	},
	{
		name: '鋼鉄の盾',
		nameEn: 'Steel Shield',
		price: '2gp',
		desc: '硬度5、HP20。シールドブロック用の標準的な盾。AC+2（掲げ時）。',
	},
	{
		name: '木製の盾',
		nameEn: 'Wooden Shield',
		price: '1gp',
		desc: '硬度3、HP12。軽量な盾。AC+2（掲げ時）。',
	},
];

// ─────────────────────────────────────
// マジックアイテム
// ─────────────────────────────────────
DB.magicItems = [
	// ルーン
	{
		name: '+1ポテンシー・ルーン（武器）',
		nameEn: 'Weapon Potency +1',
		level: 2,
		category: '武器ルーン',
		price: '35gp',
		desc: '武器の攻撃ロールに+1アイテムボーナス。',
	},
	{
		name: 'ストライキング・ルーン',
		nameEn: 'Striking Rune',
		level: 4,
		category: '武器ルーン',
		price: '65gp',
		desc: '武器のダメージダイスが2個になる。',
	},
	{
		name: '+2ポテンシー・ルーン（武器）',
		nameEn: 'Weapon Potency +2',
		level: 10,
		category: '武器ルーン',
		price: '935gp',
		desc: '武器の攻撃ロールに+2アイテムボーナス。',
	},
	{
		name: 'グレーター・ストライキング',
		nameEn: 'Greater Striking Rune',
		level: 12,
		category: '武器ルーン',
		price: '1060gp',
		desc: '武器のダメージダイスが3個になる。',
	},
	{
		name: '+3ポテンシー・ルーン（武器）',
		nameEn: 'Weapon Potency +3',
		level: 16,
		category: '武器ルーン',
		price: '8935gp',
		desc: '武器の攻撃ロールに+3アイテムボーナス。',
	},
	{
		name: 'メジャー・ストライキング',
		nameEn: 'Major Striking Rune',
		level: 19,
		category: '武器ルーン',
		price: '31060gp',
		desc: '武器のダメージダイスが4個になる。',
	},
	{
		name: 'フレイミング',
		nameEn: 'Flaming Rune',
		level: 8,
		category: '属性ルーン',
		price: '500gp',
		desc: '打撃命中時に+1d6火炎ダメージ。クリティカルで+1d10持続火炎。',
	},
	{
		name: 'ショック',
		nameEn: 'Shock Rune',
		level: 8,
		category: '属性ルーン',
		price: '500gp',
		desc: '打撃命中時に+1d6電撃ダメージ。クリティカルで+1d10持続電撃。',
	},
	// 防具ルーン
	{
		name: '+1ポテンシー・ルーン（防具）',
		nameEn: 'Armor Potency +1',
		level: 5,
		category: '防具ルーン',
		price: '160gp',
		desc: '防具のACに+1アイテムボーナス。セーヴ無効回数1回/日。',
	},
	{
		name: 'レジリエント・ルーン',
		nameEn: 'Resilient Rune',
		level: 8,
		category: '防具ルーン',
		price: '340gp',
		desc: '全セーヴィングスローに+1アイテムボーナス。',
	},
	{
		name: '+2ポテンシー・ルーン（防具）',
		nameEn: 'Armor Potency +2',
		level: 11,
		category: '防具ルーン',
		price: '1060gp',
		desc: '防具のACに+2アイテムボーナス。',
	},
	{
		name: 'グレーター・レジリエント',
		nameEn: 'Greater Resilient Rune',
		level: 14,
		category: '防具ルーン',
		price: '3440gp',
		desc: '全セーヴに+2アイテムボーナス。',
	},
	// 装着アイテム
	{
		name: '鷹の目のゴーグル',
		nameEn: 'Eyes of the Eagle',
		level: 3,
		category: '装着（目）',
		price: '60gp',
		desc: '知覚判定（視覚）に+1アイテムボーナス。',
	},
	{
		name: '夜視のゴーグル',
		nameEn: 'Goggles of Night',
		level: 5,
		category: '装着（目）',
		price: '150gp',
		desc: '暗視を得る。',
	},
	{
		name: '翼のブーツ',
		nameEn: 'Winged Boots',
		level: 10,
		category: '装着（足）',
		price: '850gp',
		desc: '1日5分間の飛行速度（分割使用可）。',
	},
	{
		name: '耐性のマント',
		nameEn: 'Cloak of Resistance',
		level: 9,
		category: '装着（肩）',
		price: '680gp',
		desc: '全セーヴに+1アイテムボーナス（レジリエント同等）。',
	},
	{
		name: '巨人力の帯',
		nameEn: 'Belt of Giant Strength',
		level: 17,
		category: '装着（腰）',
		price: '15000gp',
		desc: '筋力に+2アイテムボーナス（頂点アイテム）。',
	},
	{
		name: '知性の冠',
		nameEn: 'Diadem of Intellect',
		level: 17,
		category: '装着（頭）',
		price: '15000gp',
		desc: '知力に+2アイテムボーナス（頂点アイテム）。',
	},
	// ワンド・スタッフ
	{
		name: 'ワンド・オブ・マニフォールドミサイル',
		nameEn: 'Wand of Manifold Missiles',
		level: 5,
		category: 'ワンド',
		price: '160gp',
		desc: 'フォースバラージ使用時に追加ミサイル発射。1日1回。',
	},
	{
		name: 'ヒーリングスタッフ',
		nameEn: 'Staff of Healing',
		level: 4,
		category: 'スタッフ',
		price: '90gp',
		desc: 'ヒール関連の呪文を蓄積。チャージで使用。',
	},
	{
		name: 'パワーのスタッフ',
		nameEn: 'Staff of Power',
		level: 16,
		category: 'スタッフ',
		price: '10000gp',
		desc: '8チャージ。多数の秘術呪文を蓄積。打撃も+2ストライキング相当。',
	},
	// 特殊武器
	{
		name: 'フロストブランド',
		nameEn: 'Frost Brand',
		level: 12,
		category: '特殊武器',
		price: '2000gp',
		desc: '+2ストライキング冷気ルーン付き剣。火炎抵抗5を付与。',
	},
	{
		name: 'ホーリーアヴェンジャー',
		nameEn: 'Holy Avenger',
		level: 14,
		category: '特殊武器',
		price: '4500gp',
		desc: '+2グレーター・ストライキング聖なるルーン付き。チャンピオンの反応強化。',
	},
	{
		name: 'ヴォーパルソード',
		nameEn: 'Vorpal Sword',
		level: 17,
		category: '特殊武器',
		price: '15000gp',
		desc: '+3グレーター・ストライキング。自然20で首をはねる（頑健DC37）。',
	},
	// 盾
	{
		name: 'スペルガード・シールド',
		nameEn: 'Spellguard Shield',
		level: 8,
		category: '特殊盾',
		price: '500gp',
		desc: '呪文に対するセーヴに+2状況ボーナス。呪文ダメージに盾ブロック可能。',
	},
	{
		name: 'ライオンの盾',
		nameEn: "Lion's Shield",
		level: 6,
		category: '特殊盾',
		price: '245gp',
		desc: '1日1回、ライオンの噛み付き攻撃を行う。',
	},
	{
		name: '矢弾きの盾',
		nameEn: 'Arrow-Catching Shield',
		level: 10,
		category: '特殊盾',
		price: '900gp',
		desc: '遠隔攻撃に対して自動で盾ブロック可能。',
	},
	// ポーション
	{
		name: 'ヒーリングポーション（小）',
		nameEn: 'Minor Healing Potion',
		level: 1,
		category: 'ポーション',
		price: '4gp',
		desc: '1d8HPを回復。',
	},
	{
		name: 'ヒーリングポーション（中）',
		nameEn: 'Lesser Healing Potion',
		level: 3,
		category: 'ポーション',
		price: '12gp',
		desc: '2d8+5HPを回復。',
	},
	{
		name: 'ヒーリングポーション（大）',
		nameEn: 'Moderate Healing Potion',
		level: 5,
		category: 'ポーション',
		price: '30gp',
		desc: '3d8+10HPを回復。',
	},
	{
		name: '上級ヒーリングポーション',
		nameEn: 'Greater Healing Potion',
		level: 7,
		category: 'ポーション',
		price: '70gp',
		desc: '6d8+20HPを回復。',
	},
	{
		name: '飛行ポーション',
		nameEn: 'Potion of Flying',
		level: 8,
		category: 'ポーション',
		price: '100gp',
		desc: '飛行速度40ftを1分間得る。',
	},
	// 所持アイテム
	{
		name: 'バッグ・オブ・ホールディング I',
		nameEn: 'Bag of Holding (Type I)',
		level: 4,
		category: '所持アイテム',
		price: '75gp',
		desc: 'バルク25まで収容可能な次元間収納鞄。',
	},
	{
		name: 'バッグ・オブ・ホールディング II',
		nameEn: 'Bag of Holding (Type II)',
		level: 7,
		category: '所持アイテム',
		price: '300gp',
		desc: 'バルク50まで収容可能な次元間収納鞄。',
	},
	{
		name: 'イモーバブルロッド',
		nameEn: 'Immovable Rod',
		level: 9,
		category: '所持アイテム',
		price: '600gp',
		desc: 'ボタンを押すと空中固定。8000ポンドまで支持。',
	},
	{
		name: 'ポータブルホール',
		nameEn: 'Portable Hole',
		level: 13,
		category: '所持アイテム',
		price: '3000gp',
		desc: '直径6ft・深さ10ftの穴。畳んで持ち運び可能。',
	},
];

// ─────────────────────────────────────
// アクション (Actions)
// ─────────────────────────────────────
DB.actions = [
	{
		name: '打撃',
		nameEn: 'Strike',
		actions: 1,
		desc: '武器や素手で攻撃。MAP（-5/-10）が累積。',
	},
	{
		name: '移動',
		nameEn: 'Stride',
		actions: 1,
		desc: '速度分の距離を移動する。',
	},
	{
		name: '一歩離脱',
		nameEn: 'Step',
		actions: 1,
		desc: '5ftだけ移動。リアクションを誘発しない。',
	},
	{
		name: '相互作用',
		nameEn: 'Interact',
		actions: 1,
		desc: '物を拾う、ドアを開ける、アイテムを使うなど。',
	},
	{
		name: '盾を掲げる',
		nameEn: 'Raise a Shield',
		actions: 1,
		desc: 'ACに+2状況ボーナス（次のターン開始まで）。',
	},
	{
		name: '脱出',
		nameEn: 'Escape',
		actions: 1,
		desc: 'つかまれた・拘束状態から脱出する判定。',
	},
	{
		name: '組み付き',
		nameEn: 'Grapple',
		actions: 1,
		desc: '（運動）対象をつかむ。成功で掴まれた状態。',
	},
	{
		name: '突き飛ばし',
		nameEn: 'Shove',
		actions: 1,
		desc: '（運動）対象を5ft押しやる。',
	},
	{
		name: '足払い',
		nameEn: 'Trip',
		actions: 1,
		desc: '（運動）対象を転倒させる。',
	},
	{
		name: '武器落とし',
		nameEn: 'Disarm',
		actions: 1,
		desc: '（運動）対象の武器を落とさせる（-2ペナルティ付与）。',
	},
	{
		name: 'デモラライズ',
		nameEn: 'Demoralize',
		actions: 1,
		desc: '（威圧）対象に恐怖1を付与。クリティカルで恐怖2。',
	},
	{
		name: 'フェイント',
		nameEn: 'Feint',
		actions: 1,
		desc: '（欺瞞）成功で対象は次の攻撃に対して挟撃状態。',
	},
	{
		name: 'リコール・ナレッジ',
		nameEn: 'Recall Knowledge',
		actions: 1,
		desc: '（知識技能）敵の弱点や情報を思い出す。',
	},
	{
		name: '遅延',
		nameEn: 'Delay',
		actions: 0,
		desc: 'フリーアクション。イニシアチブ順を後に変更。',
	},
	{
		name: '待機',
		nameEn: 'Ready',
		actions: 2,
		desc: 'トリガーを設定し、条件を満たしたらリアクションで行動。',
	},
	{
		name: '探索',
		nameEn: 'Seek',
		actions: 1,
		desc: '（知覚）隠れた生物や物体を探す。',
	},
	{
		name: '立ち上がり',
		nameEn: 'Stand',
		actions: 1,
		desc: '転倒状態から立ち上がる。',
	},
	{
		name: '掴み放し',
		nameEn: 'Release',
		actions: 0,
		desc: 'フリーアクション。持っているものを放す。',
	},
];

// ─────────────────────────────────────
// GMトピック
// ─────────────────────────────────────
DB.gmTopics = [
	{
		id: 'basics',
		name: '基本ルール',
		desc: 'アクション経済（3アクション制）、判定の4段階（大成功/成功/失敗/大失敗）、DCの決め方',
	},
	{
		id: 'combat',
		name: '戦闘',
		desc: 'イニシアチブ、攻撃と防御、MAP、カバー、挟撃、状態異常',
	},
	{
		id: 'magic',
		name: '魔法',
		desc: '呪文伝統（秘術/神術/原始/オカルト）、呪文ランク、準備/自発、集中呪文',
	},
	{
		id: 'skills',
		name: '技能と探索',
		desc: '技能判定、探索モード（回避/捜索/偵察/追跡）、社交遭遇',
	},
	{
		id: 'encounter',
		name: '遭遇バランス',
		desc: '脅威度の計算、経験値配分、中程度/深刻/極端の難易度',
	},
	{
		id: 'treasure',
		name: '財宝と報酬',
		desc: 'レベル別財宝表、パーマネントアイテム、消費アイテム、通貨',
	},
	{
		id: 'conditions',
		name: '状態異常',
		desc: '恐怖/病気/麻痺/瀕死/朦朧など全状態異常の早見表',
	},
	{
		id: 'chargen',
		name: 'キャラクター作成',
		desc: '能力値、祖先、背景、クラスの選択手順とポイント',
	},
	{
		id: 'classes',
		name: 'クラス解説',
		desc: '20クラスの概要、役割、強みと弱み',
	},
	{
		id: 'ancestries',
		name: '祖先と遺産',
		desc: '7祖先の特徴、遺産の選択肢、祖先特技',
	},
];

// ─────────────────────────────────────
// 集計
// ─────────────────────────────────────
DB.totalEntries = function () {
	let t = 0;
	[
		'ancestries',
		'heritages',
		'backgrounds',
		'classes',
		'abilities',
		'skills',
		'conditions',
		'spells',
		'feats',
		'weapons',
		'armor',
		'adventuringGear',
		'magicItems',
		'actions',
		'gmTopics',
	].forEach((k) => {
		if (DB[k]) t += DB[k].length;
	});
	return t;
};
